### ISSUE TITLE
So, I have this error.

### ISSUE THREAD

**Issue by Neoslayer** [TheCBProject/CodeChickenLib#109]
Here's the log, Magic launcher, 1.12.2 etc. 

-- Head --
Thread: Client thread
Stacktrace:
    at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:126)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_113_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:175)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at magic.launcher.Launcher.main(SourceFile:214)

Maybe it has something to do with Biomes o'plenty?
I can't remove it or Enderstorage, these mods are gods.

**Comment by covers1624** [comment]
Please provide the full crash report in a pastebin link, posting a snippet is a one way street to having your issue insta closed.

**Comment by Neoslayer** [comment]
How positive. Please at least consider the fact that I'm new to this. Not only that but I haven't played this game in four years, never used pastebin, and I have no idea how GitHub works. You probably know that I have actually stated that elsewhere, the logs, which, to throw in, I have no understanding of. What I put in my post I assumed was all you needed to know because I don't think anything else in the log looked like it would make any contribution to the issue at hand..

Additionally, I downloaded both of the mods saying they were 1.12.2, (ender storage and codechicken lib) I probably downloaded it from one of those clickbait sites, I don't know, guess that was my mistake. They probably slapped the latest version on an outdated mod to reel in people or something.

I'm glad you responded so quickly though.

**Comment by covers1624** [comment]
While i understand that you may be new, the entire crash report file is generated for a reason. Regardless, having that is a must as this crash would have been reported thousands of times over if it happend normally, its probably some other mod breaking my shit. As long as you downloaded the mods from either "chickenbones.net" or "curseforge.com" then you are fine.

**Comment by Neoslayer** [comment]
Can't seem to figure out which mod it is..
I wish I would actually be able to find wherever the dang discrepancies between the two mods instead of it saying a bunch of random stuff..
;_;

Tried pastebin for the first time and it is pretty cool.
Hopefully this is what you were looking for?
https://pastebin.com/H5dCJ0u4

**Comment by covers1624** [comment]
Seems one of CCL's AccessTransformer lines aren't being applied. Sadly, you will have to strip down the pack and find the conflicting mod..

**Comment by covers1624** [comment]
Any update?
