### ISSUE TITLE
Tracker for mods using Dependency Downloader. 

### ISSUE THREAD

**Issue by covers1624** [TheCBProject/CodeChickenLib#12]
This issue is linked in the new version of the dependency downloader. Please comment a screenshot of the dependency downloader window that has linked you here. I will place the info in a table of mine and notify authors.

Back Story:
CodeChickenCore is going to be phased out entirely by my update to 1.11 (When it comes out). So in prep for that the DependencyDownloader needs to go away. This is the start of it, I need to have a list of mods still using the dependency downloader  and inform the authors that they need to stop using it for what ever reason they are.
In addition to this CodeChickenLib will NOT be downloaded even if it is requested. Instead it will remove any CCL version from /mods/<mcversion> and force people to have it in /mods and use a normal forge dpendency instead of the dependency downloader.
So. Tl;Dr CCC is going away, Deploader is cancer, CCL is not auto downloaded.

**Comment by Dlorii** [comment]
As requested good sir :)

Brandon pushed a new build 2 hours ago with the changelog:
''Updates required for latest CCL changes''

So i'm not a 100% sure if his new build isn't fully working with the dependency check or if you got to change something. Hope this helps !

![f](https://cloud.githubusercontent.com/assets/5676674/19416482/3ab50cbe-9392-11e6-8a45-4e3bc248f141.jpg)

**Comment by covers1624** [comment]
Yeah, it seems that i forgot to remove the dependencies.info file from BrandonsCore.. Like this comment so i can remove it once you have read it.

**Comment by Zeevian** [comment]
The DepLoader un-installs the current version installed during loading and then doesn't download the new/correct version.  Using Brandon's Core 1.10.2-2.1.0.51 as well  Tried with CodeChickenLib 2.4.2.106 and 2.4.1.101

**Comment by Unrepentant-Atheist** [comment]
https://imgur.com/a/1Sdz3

**Comment by Unrepentant-Atheist** [comment]
Mekkanism also doesn't work without CodeChickenLib

**Comment by covers1624** [comment]
@Zeevian The deploader will no longer auto install CCL you need to put it in your mods folder from curse, any CCL version inside mods/mcver will be auto removed.

**Comment by darkphan** [comment]
Would have been nice if there was some sort of config or what not that the CodeChickenLib kept track of locally so it would not have to pop up the window every single time a modpack was loaded with this in it...

**Comment by covers1624** [comment]
you can add -Ddeploader.dontYellAtPeople=true to your java launch arguments to dissable it

**Comment by darkphan** [comment]
Ah, thanks!

**Comment by archmage94** [comment]
Tried that, the warning didn't show up but it still deleted the file

**Comment by covers1624** [comment]
Yes, it stops the dialog but it will delete ANY file that contains "CodeChickenLib" in its name from /mods/mcver. Place CCL in your mods folder not /mods/mcver

**Comment by archmage94** [comment]
Only one problem, I get this error

2016-10-17 17:26:21,659 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-10-17 17:26:21,661 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:26:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:26:21] [main/INFO] [FML]: Forge Mod Loader version 12.18.1.2095 for Minecraft 1.10.2 loading
[17:26:21] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
2016-10-17 17:26:21,829 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-10-17 17:26:21,843 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-10-17 17:26:21,845 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[17:26:21] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:26:21] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:26:21] [main/WARN] [FML]: The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:26:21] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:26:21] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:26:21] [main/INFO] [FML]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from liteloader-1.10-SNAPSHOT-release.jar
[17:26:21] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:26:21] [main/ERROR] [FML]: The coremod li.cil.oc.common.launch.TransformerLoader is requesting minecraft version 1.10 and minecraft is 1.10.2. It will be ignored.
[17:26:21] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.10.2_HD_U_C3.jar
[17:26:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:26:21] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[17:26:21] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[17:26:21] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[17:26:22] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[17:26:22] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/C:/Users/archm/AppData/Roaming/.minecraft/mods/OptiFine_1.10.2_HD_U_C3.jar
[17:26:22] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: C:\Users\archm\AppData\Roaming\.minecraft\mods\OptiFine_1.10.2_HD_U_C3.jar
[17:26:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:23] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:26:23] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:26:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:26] [main/INFO] [IC2-core]: Loaded library EJML-core-0.26.jar.
[17:26:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:26:26] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Exception in thread "main" [17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: codechicken/core/launch/CodeChickenCorePlugin
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at codechicken.nei.asm.NEICorePlugin.getASMTransformerClass(NEICorePlugin.java:17)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:128)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: codechicken.core.launch.CodeChickenCorePlugin
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:26:26] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[17:26:26] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[17:26:26] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[17:26:26] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more

**Comment by tenten8401** [comment]
^ http://hastebin.com please.

**Comment by archmage94** [comment]
What about it?

**Comment by tenten8401** [comment]
It's for pasting things like logs so you don't have to read it horribly formatted and crushed in github.

**Comment by archmage94** [comment]
Ok

**Comment by archmage94** [comment]
Like this?
http://hastebin.com/yaqolosuko.sql

**Comment by tenten8401** [comment]
Exactly like that. It's a whole lot easier to read that way. Also, by the looks of it, you don't have CodeChickenCore installed, or you need to drop CodeChickenLib in your /mods folder instead of /mods/1.10.2

**Comment by archmage94** [comment]
Well I downloaded CodeChickenCore and made sure CodeChickenLib was in my /mods folder and I still get the error

**Comment by archmage94** [comment]
http://hastebin.com/upolamohak.sql

But in all seriousness Brandon really needs to get rid of the dependency, I love Draconic Evolution too much

**Comment by tenten8401** [comment]
I have CodeChickenCore 1.10.2-2.3.4.89 and CodeChickenLib 1.10.2-2.4.2.106 alongside Brandon's Core inside the /mods folder and it works great. If you need proof or just want a pack with draconic in it, download "IndustrialBox" on ATLauncher and copy the mods out from there.

Shameless self-promotion...

**Comment by archmage94** [comment]
I was trying to run CodeChickenLib 1.10.2-2.4.2.107. Could that have to do with it. Or perhaps it's one of my other mods?

**Comment by tenten8401** [comment]
Try it, I'm honestly not sure.

**Comment by archmage94** [comment]
And with a quick test, it has nothing to do with this issue at all, it's one of my other mods

**Comment by archmage94** [comment]
Yeah, it was Not Enough Items causing the problem (Obsolete mod I know with Just Enough Items) but I miss NEI cause it has more useful features

**Comment by covers1624** [comment]
Brandon is not going to get rid of the CCL dependency as it has lots of key features he is using behind the scenes. Like @tenten8401 is saying, it just works. Always make sure you have the latest mods before submitting any crash reports. ima remove most of the comments before this one.

**Comment by archmage94** [comment]
K

**Comment by Notawallplan** [comment]
"Modularity-[1.10.2]-0.1.0.jar" Wants: CodeChickenLib-2.2.3.57

Due to Curse, this is the latest version of this mod.

Edit: Please turn the popup box into an actual window.

**Comment by covers1624** [comment]
Closing this due to no mods are using the dep loader.
