### ISSUE TITLE
[1.12.2 Direwolf20 pack] rendering issues

### ISSUE THREAD

**Issue by skylersa** [TheCBProject/CodeChickenLib#123]
I am have been having a lot of trouble with textures including drawers, energy cells, thermal piping and refined storage piping. Thermal machines are glitching out too. the only modification i've made to the pack is adding some mt scripts.
Here are screenshots  
![image](https://user-images.githubusercontent.com/2136441/33811226-010f4fa0-ddc5-11e7-8bf7-5ff7be801f37.png)
![image](https://user-images.githubusercontent.com/2136441/33811237-2a30bb4e-ddc5-11e7-9c58-1c538ce1b0cc.png)
here's the log , this is after i close the game.
https://pastebin.com/dkj7FdJx
I have tried relogging and resarting the game and my computer

**Comment by covers1624** [comment]
```
Caused by: java.lang.NullPointerException
    at com.raoulvdberge.refinedstorage.tile.TileNode.getNode(TileNode.java:85) ~[TileNode.class:?]
    at com.raoulvdberge.refinedstorage.tile.TileNode.readUpdate(TileNode.java:72) ~[TileNode.class:?]
    at com.raoulvdberge.refinedstorage.tile.TileBase.handleUpdateTag(TileBase.java:90) ~[TileBase.class:?]
    at mcmultipart.api.multipart.IMultipartTile.handlePartUpdateTag(IMultipartTile.java:121) ~[IMultipartTile.class:?]
```  
Seems RefinedStorage crashed reading an NBT tag on the client, causing null tiles on the client.
