### ISSUE TITLE
bakery crash

### ISSUE THREAD

**Issue by sami-odematt** [TheCBProject/CodeChickenLib#139]
I read the other issue with this, but I didn't have AE2 or the other mod you said included and so I'm not sure what's going on or why I'm having this issue. The only reason I'm posting this here is because the name of this mod is the main thing in the crash report.

this is the shorten crash report. I can post the extended one if you'd like at a later time
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.block.model.ModelBakery.field_177610_k from class codechicken.lib.model.loader.blockstate.CCBlockStateLoader

**Comment by covers1624** [comment]
Always provide the full crash report.

**Comment by sami-odematt** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/20/18 10:55 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.block.model.ModelBakery.field_177610_k from class codechicken.lib.model.loader.blockstate.CCBlockStateLoader
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_102_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:172)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_102_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:172)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 498807960 bytes (475 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version         | Source                                        | Signature                                |
	|:----- |:-------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCH   | mcp                  | 9.42            | minecraft.jar                                 | None                                     |
	| UCH   | FML                  | 8.0.99.99       | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.2.2611    | forge-1.12.2-14.23.2.2611.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater    | 1.0             | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCH   | jei                  | 4.8.5.147       | jei_1.12.2-4.8.5.147.zip                      | None                                     |
	| UCH   | appleskin            | 1.0.9           | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3      | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCH   | codechickenlib       | 3.1.5.331       | CodeChickenLib-1.12.2-3.1.5.331-universal.zip | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | compactstorage       | 3.0             | CompactStorage-3.0-10.jar                     | None                                     |
	| UCH   | gravestone           | 1.10.1          | gravestone-1.10.1.jar                         | None                                     |
	| UCH   | waila                | 1.8.23          | Hwyla-1.8.23-B38_1.12.jar                     | None                                     |
	| UCH   | mantle               | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.9.1.65 | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCH   | immersiveengineering | 0.12-77         | ImmersiveEngineering-0.12-77.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | nei                  | 2.4.1           | NotEnoughItems-1.12.2-2.4.1.233-universal.zip | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | harvestcraft         | 1.12.2p         | Pam's+HarvestCraft+1.12.2p.jar                | None                                     |
	| UCH   | projecte             | 1.12-PE1.0.0    | ProjectE-1.12-PE1.2.0.zip                     | None                                     |
	| UCH   | storagedrawers       | 1.12-5.2.5      | StorageDrawers-1.12.2-5.3.4.zip               | None                                     |
	| UCH   | refinedstorage       | 1.5.31          | refinedstorage-1.5.31.zip                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | wawla                | 2.5.251         | Wawla-1.12.2-2.5.251.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-77-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4526' Renderer: 'Intel(R) HD Graphics 500'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 500 GL version 4.4.0 - Build 21.20.16.4526, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) CPU N3350 @ 1.10GHz

**Comment by covers1624** [comment]
You have CodeChickenLib installed as a zip file, it needs to be a jar file. Please change the extension of the file or re download with a proper web browser.
