### ISSUE TITLE
[1.10.2] Client freeze seems Baking issue

### ISSUE THREAD

**Issue by Marcel40625** [TheCBProject/CodeChickenLib#142]
Hey there im having a big issue

**Mods:**
CodeChickenLib-1.10.2-2.5.9.320-universal.jar
journeymap-1.10.2-5.5.2.jar
ThermalExpansion-1.10.2-5.1.10.28-universal.jar

**Problem:**
freeze when logging in near a Thermal Expansion tank on a Tconstruct smeltery
client freezes and only solution to close is kill java process

**Error Log:** 
https://pastebin.com/SU9b2WZE

```
[19:30:04] [JM-task-4/ERROR] [CodeChickenLib/]: Fatal exception thrown whilst baking block model for: thermalexpansion:tank
java.lang.NullPointerException
	at cofh.thermalexpansion.render.RenderTank.bakeLayerFace(RenderTank.java:159) ~[RenderTank.class:?]
	at codechicken.lib.model.blockbakery.BlockBakery.generateModel(BlockBakery.java:301) ~[BlockBakery.class:?]
	at codechicken.lib.model.blockbakery.BlockBakery.getCachedModel(BlockBakery.java:256) [BlockBakery.class:?]
	at codechicken.lib.model.blockbakery.CCBakeryModel.func_188616_a(CCBakeryModel.java:30) [CCBakeryModel.class:?]
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:130) [VanillaBlockSpriteProxy.class:1.10.2-5.5.2]
	at journeymap.client.mod.vanilla.VanillaBlockSpriteProxy.getSprites(VanillaBlockSpriteProxy.java:84) [VanillaBlockSpriteProxy.class:1.10.2-5.5.2]
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getSpriteColor(VanillaBlockColorProxy.java:141) [VanillaBlockColorProxy.class:1.10.2-5.5.2]
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.deriveBlockColor(VanillaBlockColorProxy.java:62) [VanillaBlockColorProxy.class:1.10.2-5.5.2]
	at journeymap.client.model.BlockMD.getTextureColor(BlockMD.java:467) [BlockMD.class:1.10.2-5.5.2]
	at journeymap.client.mod.vanilla.VanillaBlockColorProxy.getBlockColor(VanillaBlockColorProxy.java:88) [VanillaBlockColorProxy.class:1.10.2-5.5.2]
	at journeymap.client.model.BlockMD.getBlockColor(BlockMD.java:455) [BlockMD.class:1.10.2-5.5.2]
	at journeymap.client.cartography.render.BaseRenderer.setStratumColors(BaseRenderer.java:277) [BaseRenderer.class:1.10.2-5.5.2]
	at journeymap.client.cartography.Strata.nextUp(Strata.java:225) [Strata.class:1.10.2-5.5.2]
	at journeymap.client.cartography.render.SurfaceRenderer.paintStrata(SurfaceRenderer.java:448) [SurfaceRenderer.class:1.10.2-5.5.2]
	at journeymap.client.cartography.render.SurfaceRenderer.renderSurface(SurfaceRenderer.java:213) [SurfaceRenderer.class:1.10.2-5.5.2]
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:122) [SurfaceRenderer.class:1.10.2-5.5.2]
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:92) [SurfaceRenderer.class:1.10.2-5.5.2]
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:156) [ChunkRenderController.class:1.10.2-5.5.2]
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:172) [BaseMapTask.class:1.10.2-5.5.2]
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:89) [TaskBatch.class:1.10.2-5.5.2]
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:411) [MapPlayerTask$MapPlayerTaskBatch.class:1.10.2-5.5.2]
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:102) [RunnableTask$Inner.class:1.10.2-5.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

**Comment by Marcel40625** [comment]
even deleting journeymap and ThermalExpansion doesnt fix the freezing ... problem is im getting no erros because clients freezes and stops writing to logfile

**Comment by covers1624** [comment]
Those errors are useless, please provide your full log.

**Comment by Marcel40625** [comment]
nevermind ... after testing for about 9 hrs. i found the problem, it was the mod openFM for opencomputers. like i said, there where no writes in the logs because the client freezd all the time so this was the last entry and i assumed its the fault of chickenlib ... sorry!
