### ISSUE TITLE
[1.10.2] Client crash when going near Thermal Expansion Machines?!

### ISSUE THREAD

**Issue by Marcel40625** [TheCBProject/CodeChickenLib#143]
After the first bug. a second one appeared but at this time with a crash log.

dont exactly know if its related to Codechicken oder Thermal expansion

CodeChickenCore-1.10.2-2.4.1.102-universal.jar
CodeChickenLib-1.10.2-2.5.9.320-universal.jar
ThermalExpansion-1.10.2-5.1.10.28-universal.jar

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.14.137-universal.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  RefinedFixerLoadingPlugin (ImmersiveCables-1.10.2-1.2.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  DummyPlugin (ForgeEndertech-1.10.2-1.3.4.0-build.0057.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.220-universal.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.7.1.150.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/13/18 12:30 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at gcewing.architecture.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:85)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:61)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)

-- Block being tesselated --
Details:
	Block type: ID #2181 (tile.cofh.machine // cofh.thermalexpansion.block.machine.BlockMachine)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-441,71,-95), Chunk: (at 7,4,1 in -28,-6; contains blocks -448,0,-96 to -433,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at gcewing.architecture.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:85)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:61)
```

**Comment by Marcel40625** [comment]
okay has something todo with optifine ... damn shit ... closed
