### ISSUE TITLE
1.12.2 crash because of CodeChickenLib

### ISSUE THREAD

**Issue by blakjak08** [TheCBProject/CodeChickenLib#149]
Every time I try to run minecraft both in MultiMC and the java loader CodeChickenLib crashes the game saying UCEE. It doesn't matter what version the library I use. I've tried downloading from the curse website and the developers page. Also reinstalled java and that was no help either. The latest crash report is as follows: https://pastebin.com/qgLYwzeF

**Comment by Cyancraft** [comment]
It's failing at Pre-Initialization.

My crash is similar; something to do with Java erroring and the CCBlockStateLoader.

**Comment by blakjak08** [comment]
what does that mean?

**Comment by Cyancraft** [comment]
Edited my comment.

With mine in particular, it's erroring in the CCBlockStateLoader because there is something wrong with Java.

covers1624 said to try reinstalling Java. The only thing I'd recommend is uninstalling Java, reboot PC, and reinstall Java, using Java 1.8.0_151 or later. I'm using 151, and it seems to work for me, but my friend is using 171, and has this crash.

**Comment by blakjak08** [comment]
I've tried both of them for the past several hours and I still get the same thing...I read all the comments before I started asking questions

**Comment by Cyancraft** [comment]
What does it say in the Crash Report? Right before the part you pasted, i mean...

Mine:
Description: There was a severe problem during mod loading that has caused the game to fail
 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.nio.file.ProviderNotFoundException: Provider not found
    at java.nio.file.FileSystems.newFileSystem(Unknown Source)
    at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.loadFactories(CCBlockStateLoader.java:83)
    at java.util.ArrayList.forEach(Unknown Source)
    at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.initialize(CCBlockStateLoader.java:73)
    at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:54)
    at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:47)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by blakjak08** [comment]
hang on and i'll post the full report

**Comment by blakjak08** [comment]
[https://pastebin.com/8jDdSpkP](url) heres the full report

**Comment by Cyancraft** [comment]
Yep, it's the exact same error. Pastebin line #360.

>java.nio.file.ProviderNotFoundException: Provider not found

**Comment by blakjak08** [comment]
does it make a difference if i'm only running 64-bit java and not both 32 and 64?

**Comment by Cyancraft** [comment]
It's recommended to only use the Java that matches your system Architecture. If you have 32 bit Windows, use 32 bit Java. If you have 64 bit Windows, use 64 bit Java.

You are using 64 bit, and you have more than 4GB allocated (32 bit only allows a max of 4GB RAM), so you should only be using 64 bit Java.

I'm personally using
>forge14.23.3.2691
>CodeChickenLib-1.12.2-3.1.8.341-universal
>Java 64 bit jre1.8.0_151

and my JVM arguments are set to
>-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m

I noticed that you don't have the -XX:PermSize=256m part, so yours defaults to PermSize=128m, I believe.

Again, I don't have this issue on my machine, but somebody using my modpack has this issue, so I'm super invested in this problem lol

**Comment by blakjak08** [comment]
my permgen is set to 256mb and i have a min of 2 gb and max of 5gb. and only using the 64-bit

**Comment by blakjak08** [comment]
just say where that isn't showing up on the report, i'be got it set to 265 but it's not showing up

**Comment by Cyancraft** [comment]
Line 427 on your paste.

Compared to line 87 here: https://pastebin.com/387GSwrP (friend's crash report)

**Comment by Cyancraft** [comment]
Okay, so I believe I fully understand everything here.

The Throw at line 360 in your report is caused if a provider supporting the URI scheme is not installed. This happens if the JRE path isn't specified in Windows.

I'd say check the Environment variables...make sure the path is specified.

**Comment by blakjak08** [comment]
And how would I go about doing that?

**Comment by Cyancraft** [comment]
https://www.java.com/en/download/help/path.xml

Windows 10 and Windows 8
-In Search, search for and then select: System (Control Panel)
-Click the Advanced system settings link.
-Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
-In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.

**Comment by covers1624** [comment]
Providing a snippit of your crash report is not acceptable, never again please, the entire thing is generated for a reason. Anyway, this is a duplicate.

**Comment by blakjak08** [comment]
@covers1624 a duplicate of what? and I'm sorry I didn't know you needed the whole thing. Why would Mojang put int *crash report* if that wasn't going to help solve the problem. @Cyancraft So I found out another issue was the folder was in OneDrive, so I deleted that and it seems to help, at least I got a game going for now

**Comment by covers1624** [comment]
Duplicate of https://github.com/TheCBProject/CodeChickenLib/issues/148

**Comment by Cyancraft** [comment]
@blakjak08 Yeah, I've seen similar issues with people using OneDrive instead of Documents (or wherever the default is; Documents/Curse is the default for mine.

Actually, I could check to see if my friend has his set up in OneDrive. Knowing him, it's probably what the issue is.

**Comment by petrovsn** [comment]
Minecraft 12.2, Codechickenlibs 3.1.9.344.
Game crashed during pre-initializing, log is  the next:
[crash-2018-06-24_00.11.58-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130244/crash-2018-06-24_00.11.58-client.txt)
