### ISSUE TITLE
Minecraft crashing while initializing mods

### ISSUE THREAD

**Issue by ryanthevy** [TheCBProject/CodeChickenLib#156]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

Someone please help. I don't know how to fix this, I've reinstalled minecraft a couple times, codechicken lib many times, and reinstalled forge. I also updated my drivers and reinstalled java.
Heres the crash report:  https://pastebin.com/4hPkNLWq

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 6/19/18 12:43 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type  , @Line:1,                                                                                                                               
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type  , @Line:1,                                                                                                                               
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:84)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 737375224 bytes (703 MB) / 1291845632 bytes (1232 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 23 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                  | Source                                            | Signature                                |
	|:----- |:--------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft       | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCH   | mcp             | 9.42                     | minecraft.jar                                     | None                                     |
	| UCH   | FML             | 8.0.99.99                | forge-1.12.2-14.23.4.2705.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge           | 14.23.4.2705             | forge-1.12.2-14.23.4.2705.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore    | 0.11.5                   | minecraft.jar                                     | None                                     |
	| UCH   | backpack        | 3.0.2                    | backpack-3.0.2-1.12.2.jar                         | None                                     |
	| UCEE  | codechickenlib  | 3.1.9.344                | CodeChickenLib-1.12.2-3.1.9.344-universal (2).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | chickenchunks   | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | jei             | 4.10.0.198               | jei_1.12.2-4.10.0.198.jar                         | None                                     |
	| UC    | mantle          | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UC    | tconstruct      | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                   | None                                     |
	| UC    | extrautils2     | 1.0                      | extrautils2-1.12-1.7.6.jar                        | None                                     |
	| UC    | cfm             | 4.2.0                    | furniture-4.2.0-1.12.2.jar                        | None                                     |
	| UC    | gravestone      | 1.10.1                   | gravestone-1.10.1.jar                             | None                                     |
	| UC    | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest       | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| UC    | llibrary        | 1.7.14                   | llibrary-1.7.14-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | jurassicraft    | 2.1.7                    | JurassiCraft-1.12.2-2.1.7.jar                     | None                                     |
	| UC    | openmods        | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks      | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | torohealthmod   | 1.12.2-11                | torohealth-1.12.2-11.jar                          | None                                     |
	| UC    | twilightforest  | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar       | None                                     |
	| UC    | xaerominimap    | 1.14.9.1                 | Xaeros_Minimap_1.14.9.1_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11016.4' Renderer: 'AMD Radeon HD 7700 Series'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

**Comment by HeroOfFire45** [comment]
Issue is not unique to this player - I'm having the same issue.

It's also a persistent bugger, shown by these similar crash-logs that occurred in the same hour:
[crash-2018-06-23_23.02.41-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130508/crash-2018-06-23_23.02.41-client.txt)
[crash-2018-06-23_23.03.36-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130509/crash-2018-06-23_23.03.36-client.txt)
[crash-2018-06-23_23.04.14-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130510/crash-2018-06-23_23.04.14-client.txt)
[crash-2018-06-23_23.08.26-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130511/crash-2018-06-23_23.08.26-client.txt)
[crash-2018-06-23_23.13.02-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130512/crash-2018-06-23_23.13.02-client.txt)
[crash-2018-06-23_23.25.55-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130513/crash-2018-06-23_23.25.55-client.txt)
[crash-2018-06-23_23.28.33-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130514/crash-2018-06-23_23.28.33-client.txt)
[crash-2018-06-23_23.30.19-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130515/crash-2018-06-23_23.30.19-client.txt)
[crash-2018-06-23_23.33.10-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/2130516/crash-2018-06-23_23.33.10-client.txt)

Minecraft version: 1.12.2
Forge version: 14.21.1.2443 (Not the recommended version, may be a bug within Forge itself, requires sleuthing)
Mod version: 3.20

**Comment by covers1624** [comment]
Half those crash reports arent even 1.12 or CCL, The fix for this is to nuke CCL's config. `config/codechickenlib.cfg`. Theres nothing i can do if you break the config, and crashing the game so you can fix it is better then nuking the file. EDIT: Infact i can even just rename the file and error to the console.

**Comment by HeroOfFire45** [comment]
Guessing I accidentally also grabbed some logs for when I was seeing if I could get another mod to work. Anyway, I'll reset the config.

EDIT: Found the issue, apparently CodeChickenCore and CodeChickenLib no longer like being in the same space despite being for different versions.
