### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by Greatone123** [TheCBProject/CodeChickenLib#168]
I'm not sure if I should post this here, or over at the code chicken GitHub so I'm posting at both since it mentions both mods. I'm getting this constantly in my log.

MrTJPCore-1.12.2-2.1.3.35-universal
CodeChickenLib-1.12.2-3.2.0.345-universal

```
> [09:09:43] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
> java.util.concurrent.ExecutionException: java.util.NoSuchElementException: key not found: 1
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> Caused by: java.util.NoSuchElementException: key not found: 1
> 	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[MapLike$class.class:?]
> 	at scala.collection.AbstractMap.default(Map.scala:59) ~[AbstractMap.class:?]
> 	at scala.collection.mutable.HashMap.apply(HashMap.scala:65) ~[HashMap.class:?]
> 	at mrtjp.core.data.KeyTracking$.updatePlayerKey(KeyTracking.scala:28) ~[KeyTracking$.class:?]
> 	at mrtjp.core.handler.MrTJPCoreSPH$.handlePacket(packethandlers.scala:64) ~[MrTJPCoreSPH$.class:?]
> 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:135) ~[PacketCustom$ServerInboundHandler.class:?]
> 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:133) ~[PacketCustom$ServerInboundHandler.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 5 more
```

**Comment by covers1624** [comment]
You didn't need to open 2 issues, both tj and i are devs on both the mods. This appears to be an issue in TJCore however.
