### ISSUE TITLE
Crashes when it get to CodechickenLib

### ISSUE THREAD

**Issue by Blazecraft311** [TheCBProject/CodeChickenLib#179]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-83.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  HCASM (HammerCore-1.12.2-2.0.0.3.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  BCModPlugin (backpacks1.12.2-3.5.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 8/28/18 1:57 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.nio.file.ProviderNotFoundException: Provider not found
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.loadFactories(CCBlockStateLoader.java:83)
	at java.util.ArrayList.forEach(Unknown Source)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.initialize(CCBlockStateLoader.java:73)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:59)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5733498184 bytes (5467 MB) / 8006926336 bytes (7636 MB) up to 8006926336 bytes (7636 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8000m -Xmx8000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2739 Optifine OptiFine_1.12.2_HD_U_E2 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                              | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                         | 1.12.2                   | minecraft.jar                                       | None                                     |
	| UCH   | mcp                               | 9.42                     | minecraft.jar                                       | None                                     |
	| UCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2739-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                             | 14.23.4.2739             | forge-1.12.2-14.23.4.2739-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore                     |                          | minecraft.jar                                       | None                                     |
	| UCH   | openmodscore                      | 0.11.5                   | minecraft.jar                                       | None                                     |
	| UCH   | actuallyadditions                 | 1.12.2-r135              | ActuallyAdditions-1.12.2-r135.jar                   | None                                     |
	| UCH   | ic2                               | 2.8.90-ex112             | industrialcraft-2-2.8.90-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | advanced_solar_panels             | 4.2.0                    | Advanced_Solar_Panels-4.2.0.jar                     | None                                     |
	| UCH   | appliedenergistics2               | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar               | None                                     |
	| UCH   | bdlib                             | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                        | None                                     |
	| UCH   | ae2stuff                          | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                       | None                                     |
	| UCH   | backpacks16840                    | 3.5.2                    | backpacks1.12.2-3.5.2.jar                           | None                                     |
	| UCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                              | None                                     |
	| UCH   | bibliocraft                       | 2.4.5                    | BiblioCraftv2.4.5MC1.12.2.jar                       | None                                     |
	| UCH   | biomesoplenty                     | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar       | None                                     |
	| UCH   | guideapi                          | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                         | None                                     |
	| UCH   | bloodmagic                        | 1.12.2-2.3.1-99          | BloodMagic-1.12.2-2.3.1-99.jar                      | None                                     |
	| UCEE  | codechickenlib                    | 3.2.1.351                | CodeChickenLib-1.12.2-3.2.1.351-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | brandonscore                      | 2.4.3                    | BrandonsCore-1.12.2-2.4.3.168-universal.jar         | None                                     |
	| UC    | buildcraftlib                     | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcraftcore                    | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcraftbuilders                | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcraftenergy                  | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcraftfactory                 | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcraftrobotics                | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcrafttransport               | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | buildcraftsilicon                 | 7.99.17                  | buildcraft-7.99.17.jar                              | None                                     |
	| UC    | jei                               | 4.11.0.212               | jei_1.12.2-4.11.0.212_1.jar                         | None                                     |
	| UC    | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                            | None                                     |
	| UC    | natura                            | 1.12.2-4.3.2.62          | natura-1.12.2-4.3.2.62.jar                          | None                                     |
	| UC    | forestry                          | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                       | None                                     |
	| UC    | buildcraftcompat                  | 7.99.14                  | buildcraft-compat-7.99.14.jar                       | None                                     |
	| UC    | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| UC    | cofhcore                          | 4.5.3                    | CoFHCore-1.12.2-4.5.3.20-universal.jar              | None                                     |
	| UC    | cofhworld                         | 1.2.0                    | CoFHWorld-1.12.2-1.2.0.5-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | endercore                         | 1.12.2-0.5.31            | EnderCore-1.12.2-0.5.31.jar                         | None                                     |
	| UC    | thaumcraft                        | 6.1.BETA23               | Thaumcraft-1.12.2-6.1.BETA23.jar                    | None                                     |
	| UC    | thermalfoundation                 | 2.5.0                    | ThermalFoundation-1.12.2-2.5.0.19-universal (1).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | draconicevolution                 | 2.3.12                   | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar  | None                                     |
	| UC    | thermalexpansion                  | 5.5.0                    | ThermalExpansion-1.12.2-5.5.0.29-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | enderio                           | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderiointegrationtic             | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | twilightforest                    | 3.8.654                  | twilightforest-1.12.2-3.8.654-universal.jar         | None                                     |
	| UC    | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                     | None                                     |
	| UC    | conarm                            | 1.0.2                    | conarm-1.12.2-1.0.2.jar                             | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UC    | enderiobase                       | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderioconduits                   | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderioconduitsappliedenergistics | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderioconduitsopencomputers      | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderioconduitsrefinedstorage     | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderiointegrationforestry        | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderiointegrationticlate         | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderiomachines                   | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderiopowertools                 | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                           | None                                     |
	| UC    | enderstorage                      | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | exnihilocreatio                   | 1.12-0.2.4               | exnihilocreatio-1.12-0.2.4.jar                      | None                                     |
	| UC    | excompressum                      | 3.0.24                   | ExCompressum_1.12.2-3.0.24.jar                      | None                                     |
	| UC    | extrautils2                       | 1.0                      | Extra-Utilities-Mod-1.12.2.jar                      | None                                     |
	| UC    | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
	| UC    | extracells                        | 2.5.13                   | ExtraCells-1.12.2-2.5.13a60.jar                     | None                                     |
	| UC    | galacticraftcore                  | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar               | None                                     |
	| UC    | galacticraftplanets               | 4.0.1.181                | Galacticraft-Planets-1.12.2-4.0.1.181.jar           | None                                     |
	| UC    | mjrlegendslib                     | 1.12.2-1.1.4             | MJRLegendsLib-1.12.2-1.1.4.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UC    | extraplanets                      | 1.12.2-0.4.2             | ExtraPlanets-1.12.2-0.4.2.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UC    | zerocore                          | 1.12-0.1.2.2             | zerocore-1.12-0.1.2.2 (1).jar                       | None                                     |
	| UC    | bigreactors                       | 1.12.2-0.4.5.49          | ExtremeReactors-1.12.2-0.4.5.49.jar                 | None                                     |
	| UC    | hammercore                        | 2.0.0.3                  | HammerCore-1.12.2-2.0.0.3.jar                       | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UC    | ichunutil                         | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                          | None                                     |
	| UC    | hats                              | 7.0.0                    | Hats-1.12.2-7.0.2.jar                               | None                                     |
	| UC    | icbmclassic                       | 1.12.2-3.1.0.38          | ICBM-classic-1.12.2-3.1.0b38.jar                    | None                                     |
	| UC    | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest                         | 1.12.2-7.0.44.829        | ironchest-1.12.2-7.0.44.829.jar                     | None                                     |
	| UC    | harvestcraft                      | 1.12.2y                  | PamsHarvestCraft1.12.2y.jar                         | None                                     |
	| UC    | jehc                              | 1.12.2                   | JEHC-1.12.2-1.6.1.0.jar                             | None                                     |
	| UC    | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                         | None                                     |
	| UC    | mekanism                          | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                      | None                                     |
	| UC    | mekanismgenerators                | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar            | None                                     |
	| UC    | mekanismtools                     | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar                 | None                                     |
	| UC    | mousetweaks                       | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                        | None                                     |
	| UC    | recipehandler                     | 0.10                     | NoMoreRecipeConflict-0.101.12.2.jar                 | None                                     |
	| UC    | nuclearcraft                      | 2.10p                    | NuclearCraft-2.10p--1.12.2.jar                      | None                                     |
	| UC    | openmods                          | 0.11.5                   | OpenModsLib-1.12.2-0.11.5.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks                        | 1.7.6                    | OpenBlocks-1.12.2-1.7.6.jar                         | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openglider                        | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                         | None                                     |
	| UC    | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                  | None                                     |
	| UC    | simplequarry                      | 22r                      | SimpleQuarry-1.12.2-22r.jar                         | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UC    | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                     | None                                     |
	| UC    | thermaldynamics                   | 2.5.1                    | ThermalDynamics-1.12.2-2.5.1.14-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar                 | None                                     |
	| UC    | tp                                | 3.2.29                   | tinyprogressions-1.12.2-3.3.29-Release.jar          | None                                     |
	| UC    | immersiveengineering              | 0.12-83                  | ImmersiveEngineering-0.12-83.jar                    | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-83.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
HCASM (HammerCore-1.12.2-2.0.0.3.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
BCModPlugin (backpacks1.12.2-3.5.2.jar)
  brad16840.core.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4939' Renderer: 'Intel(R) UHD Graphics 630'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 307 names; 506 stacks.
Pastebin Connection: Failed!
	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r135.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-11.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.49.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.3.1-99.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.17.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.17.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.17.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.17.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.17.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.17.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.5.3.20-universal.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.12.297-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.26.jar
		* ExCompressum|API (1.0) from ExCompressum_1.12.2-3.0.24.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.1.322.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.1.322.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.12.2-4.0.1.181.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.6-61.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-83.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-83.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.11.0.212_1.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.13.349.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* Open Glider|API (0.1) from OpenGlider-1.12.1-1.1.0.jar
		* openblocks|api (1.2) from OpenBlocks-1.12.2-1.7.6.jar
		* SimpleQuarry|API (1) from SimpleQuarry-1.12.2-22r.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.7.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA23.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* zerocore|API|multiblock (1.9.4-0.0.1) from NuclearCraft-2.10p--1.12.2.jar
		* zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from NuclearCraft-2.10p--1.12.2.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2 (1).jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2 (1).jar
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 23.20.16.4939
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by Blazecraft311** [comment]
It was a one drive problem it was downloading files as i needed them
