### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xXjojojXx** [TheCBProject/CodeChickenLib#187]
[08:41:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:41:59] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:41:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[08:41:59] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2705 for Minecraft 1.12.2 loading
[08:41:59] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_51
[08:41:59] [main/INFO] [FML]: Searching C:\Users\jojo\AppData\Roaming\.minecraft\mods for mods
[08:41:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:41:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[08:41:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:41:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:41:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:01] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[08:42:01] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[08:42:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:42:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[08:42:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[08:42:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[08:42:01] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[08:42:02] [main/INFO] [net.minecraft.client.Minecraft]: Setting user: XXXXJOJOXXXX
[08:42:04] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[08:42:04] [main/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[08:42:05] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 300687040 bytes (286 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
[08:42:05] [main/INFO] [FML]: MinecraftForge v14.23.4.2705 Initialized
[08:42:05] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[08:42:05] [main/INFO] [FML]: Replaced 1036 ore ingredients
[08:42:05] [main/INFO] [FML]: Searching C:\Users\jojo\AppData\Roaming\.minecraft\mods for mods
[08:42:06] [main/WARN] [FML]: Mod codechickenlib is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 3.2.1.351
[08:42:06] [main/INFO] [FML]: Forge Mod Loader has identified 17 mods to load
[08:42:06] [main/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod codechickenlib (CodeChicken Lib) requires [forge@[14.23.4.2718,)]
[08:42:06] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod codechickenlib (CodeChicken Lib) requires [forge@[14.23.4.2718,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[08:42:06] [main/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[08:42:06] [main/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Ancient Warfare Automation, FMLFileResourcePack:Ancient Warfare Core, FMLFileResourcePack:Ancient Warfare NPCs, FMLFileResourcePack:Ancient Warfare Structures, FMLFileResourcePack:Ancient Warfare Vehicles, FMLFileResourcePack:CodeChicken Lib, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Pixelmon, FMLFileResourcePack:Reborn Core, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:Pixelmon TCG, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Treecapitator
[08:42:06] [main/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[08:42:07] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 56710365 nanos
[08:42:07] [main/WARN] [net.minecraft.client.audio.SoundHandler]: File pixelmon:sounds/pixelmon/regis.ogg does not exist, cannot add it to event pixelmon:pixelmon.mob.regice
[08:42:07] [main/WARN] [net.minecraft.client.audio.SoundHandler]: File pixelmon:sounds/pixelmon/regis.ogg does not exist, cannot add it to event pixelmon:pixelmon.mob.regirock
[08:42:07] [main/WARN] [net.minecraft.client.audio.SoundHandler]: File pixelmon:sounds/pixelmon/regis.ogg does not exist, cannot add it to event pixelmon:pixelmon.mob.registeel
[08:42:07] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[08:42:07] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[08:42:07] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[08:42:07] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[08:42:08] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[08:42:08] [main/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded

**Comment by covers1624** [comment]
`Mod codechickenlib (CodeChicken Lib) requires [forge@[14.23.4.2718,)]` Update your forge.
