### ISSUE TITLE
Crashing whenever I start the game (with crash report)

### ISSUE THREAD

**Issue by TonyBouru** [TheCBProject/CodeChickenLib#198]
Whenever I start the game it crashes, yes I do have the latest forge version, I have tried using older versions but It won't let me use them for a mod that I want to play with (Ancient Warfare). I have deleted the configs for it as well, still won't work.

Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCore (movingworld-1.12-6.342-full (1).jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/6/18 12:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:6, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 417445896 bytes (398 MB) / 1207959552 bytes (1152 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version          | Source                                             | Signature                                |
	|:----- |:-------------------------------------------- |:---------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                                    | 1.12.2           | minecraft.jar                                      | None                                     |
	| UCH   | mcp                                          | 9.42             | minecraft.jar                                      | None                                     |
	| UCH   | FML                                          | 8.0.99.99        | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                                        | 14.23.5.2768     | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | com.elytradev.movingworld.common.asm.coremod |                  | minecraft.jar                                      | None                                     |
	| UCEE  | codechickenlib                               | 3.2.1.349        | CodeChickenLib-1.12.2-3.2.1.349-universal (1).jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | ancientwarfare                               | 1.12.2-2.6.1.390 | ancientwarfare-1.12.2-2.6.1.390 (1).jar            | None                                     |
	| UC    | ancientwarfareautomation                     | 1.12.2-2.6.1.390 | ancientwarfare-1.12.2-2.6.1.390 (1).jar            | None                                     |
	| UC    | ancientwarfarenpc                            | 1.12.2-2.6.1.390 | ancientwarfare-1.12.2-2.6.1.390 (1).jar            | None                                     |
	| UC    | ancientwarfarestructure                      | @VERSION@        | ancientwarfare-1.12.2-2.6.1.390 (1).jar            | None                                     |
	| UC    | ancientwarfarevehicle                        | 1.12.2-2.6.1.390 | ancientwarfare-1.12.2-2.6.1.390 (1).jar            | None                                     |
	| UC    | antiqueatlas                                 | 4.4.9            | antiqueatlas-1.12.2-4.4.9.jar                      | None                                     |
	| UC    | antiqueatlasoverlay                          | 1.2              | antiqueatlas-1.12.2-4.4.9.jar                      | None                                     |
	| UC    | examplemod                                   | 1.0              | antiqueatlas-1.12.2-4.4.9.jar                      | None                                     |
	| UC    | gorecore                                     | 1.12.2-0.4.5     | avatarmod+a5.9.1-alpha.jar                         | None                                     |
	| UC    | avatarmod                                    | unspecified      | avatarmod+a5.9.1-alpha.jar                         | None                                     |
	| UC    | bettercompass                                | 1.5.0            | bettercompass-1.12.2-1.5.0.jar                     | None                                     |
	| UC    | bibliocraft                                  | 2.4.5            | BiblioCraft[v2.4.5][MC1.12.2] (2).jar              | None                                     |
	| UC    | bookshelf                                    | 2.3.566          | Bookshelf-1.12.2-2.3.566.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | gamestages                                   | 2.0.106          | GameStages-1.12.2-2.0.106.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | carryon                                      | 1.11.1           | CarryOn+MC1.12.2+v1.11.1.jar                       | None                                     |
	| UC    | containerfix                                 | 1.0              | ContainerFix+MC1.12.2+v1.0.jar                     | None                                     |
	| UC    | movingworld                                  | 1.12-6.342       | movingworld-1.12-6.342-full (1).jar                | None                                     |
	| UC    | davincisvessels                              | @DVESSELSVER@    | davincisvessels-1.12-6.340-full (1).jar            | None                                     |
	| UC    | ebwizardry                                   | 4.1.2            | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2 (1).jar | None                                     |
	| UC    | gottschcore                                  | 1.5.0            | GottschCore-mc1.12.2-f14.23.4.2705-v1.5.0.jar      | None                                     |
	| UC    | grapplemod                                   | 1.12.2-v11.1     | grapplemod-v11.1-1.12.2 (1).jar                    | None                                     |
	| UC    | llibrary                                     | 1.7.15           | llibrary-1.7.15-1.12.2 (3).jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | iceandfire                                   | 1.5.2            | iceandfire-1.5.2 (2).jar                           | None                                     |
	| UC    | jjcoa                                        | 1.0.9            | JJ+Coats+of+Arms+1.12-1.12.2-v1.0.9 (3).jar        | None                                     |
	| UC    | jaff                                         | 1.7_for_1.12     | JustAFewFish-1.7_for_1.12 (2).jar                  | None                                     |
	| UC    | mantle                                       | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24 (2).jar                       | None                                     |
	| UC    | mowziesmobs                                  | 1.4.2            | mowziesmobs-1.4.2 (3).jar                          | None                                     |
	| UC    | nomisma                                      | 0.1.1            | Nomisma-1.12.2-0.1.1 (4).jar                       | None                                     |
	| UC    | pirates                                      | 0.0.2            | pirates-0.0.2.jar                                  | None                                     |
	| UC    | reforged                                     | 0.7.5            | Reforged-0.7.5-1.12+ (4).jar                       | None                                     |
	| UC    | shipwrecks_winslow                           | 2.0.0            | Shipwrecks-Mod-1.12.2.jar                          | None                                     |
	| UC    | tconstruct                                   | 1.12.2-2.10.1.87 | TConstruct-1.12.2-2.10.1.87 (1).jar                | None                                     |
	| UC    | treasure2                                    | 1.0.1            | Treasure2-mc1.12.2-f14.23.4.2705-v1.0.1.jar        | None                                     |
	| UC    | worldedit                                    | 6.1.8            | worldedit-forge-mc1.12-6.1.8-dist (7).jar          | None                                     |
	| UC    | drplibrary                                   | 1.12.2-0.1.1.5   | drplibrary-1.12.2-0.1.1.5.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcmblueprints                              | 1.12.2-1.2.2     | drpcmblueprints-1.12.2-1.2.2.jar                   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcmdates                                   | 1.12.2-1.0.2     | drpcmdates-1.12.2-1.0.2.jar                        | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcmcrops                                   | 1.12.2-1.0.5     | drpcmcrops-1.12.2-1.0.5.jar                        | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpcore                                      | 1.12.2-0.4.5     | drpcore-1.12.2-0.4.5.jar                           | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UC    | drpmedieval                                  | 0.2.7.2          | drpmedieval-1.12.2-0.2.7.3.jar                     | None                                     |
	| UC    | drpcmmaarg                                   | 1.12.2-0.9.9     | drpcmmaarg-1.12.2-0.9.9.jar                        | 893c317856cf6819b3a8381c5664e4b06df7d1cc |

	Loaded coremods (and transformers): 
MovingWorldCore (movingworld-1.12-6.342-full (1).jar)
  
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

Please help. Thanks.

**Comment by covers1624** [comment]
You clearly haven't deleted the configs, this is the exact crash caused by an invalid config. `config/codechickenlib.cfg`
