### ISSUE TITLE
NPE from codechickenlib when searching JEI

### ISSUE THREAD

**Issue by Daenyth** [TheCBProject/CodeChickenLib#213]
I was searching JEI for `iron ore`, and as soon as I got to `ir`, my client crashed with 

```
java.lang.NullPointerException: Rendering ingredient
	at appeng.thirdparty.codechicken.lib.model.pipeline.transformers.QuadReInterpolator.setInputQuad(QuadReInterpolator.java:62)
	at appeng.thirdparty.codechicken.lib.model.pipeline.QuadTransformer.setInputQuad(QuadTransformer.java:93)
	at appeng.thirdparty.codechicken.lib.model.pipeline.BakedPipeline.onFull(BakedPipeline.java:274)
	at appeng.thirdparty.codechicken.lib.model.pipeline.BakedPipeline.put(BakedPipeline.java:253)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
```

It's fully reproducible - same actions result in the same crash again

Full log: https://paste.ee/p/MXvQY

**Comment by covers1624** [comment]
Please open this issue on the AE repo.

**Comment by Daenyth** [comment]
Applied energistics?

**Comment by Daenyth** [comment]
Seems to be already reported https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3810
