### ISSUE TITLE
Caught exception from CodeChicken Lib while opening Minecraft forge 1.12.2-14.23.5.2768.

### ISSUE THREAD

**Issue by Prodabic** [TheCBProject/CodeChickenLib#218]
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:84)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)

**Comment by ShplootleJess** [comment]
I'm having the same problem. It appears CodeChickenLib versions 3.1.9.344 and newer are broken with Forge

**Comment by MineRobber9000** [comment]
@ShplootleJess your issue **is** the same one as here. Delete your old CCL config. CCL isn't broken, there have simply been changes.

**Comment by ShplootleJess** [comment]
> @ShplootleJess your issue **is** the same one as here. Delete your old CCL config. CCL isn't broken, there have simply been changes.

I have, and it didn't resolve the issue, as I stated in my since-closed report.

**Comment by MineRobber9000** [comment]
@ShplootleJess can you post a current crash report in that issue

**Comment by covers1624** [comment]
Duplicate, Please delete your old CCL config file at `config/codechickenlib.cfg`.
