### ISSUE TITLE
Crash - I've given full crash report hoping someone could help 1.12.2

### ISSUE THREAD

**Issue by Idkyet124** [TheCBProject/CodeChickenLib#227]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 3/14/19 8:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1127851320 bytes (1075 MB) / 1778384896 bytes (1696 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 Optifine OptiFine_1.12.2_HD_U_E3 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                 | Source                                            | Signature                                |
	|:----- |:--------------------- |:----------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2                  | minecraft.jar                                     | None                                     |
	| UCH   | mcp                   | 9.42                    | minecraft.jar                                     | None                                     |
	| UCH   | FML                   | 8.0.99.99               | forge-1.12.2-14.23.5.2772.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.5.2772            | forge-1.12.2-14.23.5.2772.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | bibliocraft           | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| UCH   | blockarmor            | 2.4.11                  | BlockArmor-1.12.2-2.4.11.jar                      | None                                     |
	| UCH   | guideapi              | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| UCH   | bloodmagic            | 1.12.2-2.4.0-102        | BloodMagic-1.12.2-2.4.0-102.jar                   | None                                     |
	| UCH   | bookshelf             | 2.3.577                 | Bookshelf-1.12.2-2.3.577.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCEE  | codechickenlib        | 3.2.2.353               | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux          | 2.1.0                   | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | cofhcore              | 4.6.2                   | CoFHCore-1.12.2-4.6.2.25-universal.jar            | None                                     |
	| UC    | extendedrenderer      | v1.0                    | coroutil-1.12.1-1.2.13.jar                        | None                                     |
	| UC    | coroutil              | 1.12.1-1.2.13           | coroutil-1.12.1-1.2.13.jar                        | None                                     |
	| UC    | configmod             | v1.0                    | coroutil-1.12.1-1.2.13.jar                        | None                                     |
	| UC    | ptrmodellib           | 1.0.4                   | PTRLib-1.0.4.jar                                  | None                                     |
	| UC    | props                 | 2.6.2                   | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
	| UC    | mocreatures           | 12.0.5                  | DrZharks+MoCreatures+Mod-12.0.5.jar               | None                                     |
	| UC    | eplus                 | 5.0.176                 | EnchantingPlus-1.12.2-5.0.176.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | extrautils2           | 1.0                     | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| UC    | jei                   | 4.14.0.231              | jei_1.12.2-4.14.0.231.jar                         | None                                     |
	| UC    | mantle                | 1.12-1.3.2.24           | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UC    | natura                | 1.12.2-4.3.2.62         | natura-1.12.2-4.3.2.62.jar                        | None                                     |
	| UC    | forestry              | 5.8.2.366               | forestry_1.12.2-5.8.2.366.jar                     | None                                     |
	| UC    | forgelin              | 1.8.2                   | Forgelin-1.8.2.jar                                | None                                     |
	| UC    | forgemultipartcbe     | 2.6.0.79                | ForgeMultipart-1.12.2-2.6.0.79-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | microblockcbe         | 2.6.0.79                | ForgeMultipart-1.12.2-2.6.0.79-universal.jar      | None                                     |
	| UC    | minecraftmultipartcbe | 2.6.0.79                | ForgeMultipart-1.12.2-2.6.0.79-universal.jar      | None                                     |
	| UC    | inventorytweaks       | 1.64+dev.146.2180b27    | InventoryTweaks-1.64+dev.146.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest             | 1.12.2-7.0.59.842       | ironchest-1.12.2-7.0.59.842.jar                   | None                                     |
	| UC    | ironfurnaces          | 1.3.1                   | ironfurnaces-1.3.1.jar                            | None                                     |
	| UC    | librarianlib          | 4.15                    | librarianlib-1.12.2-4.15.jar                      | None                                     |
	| UC    | torohealthmod         | 1.12.2-11               | torohealth-1.12.2-11.jar                          | None                                     |
	| UC    | vampirism             | 1.5.0-alpha+03-09-16-16 | Vampirism-1.12.2-1.5.0-alpha+03-09-16-16.jar      | None                                     |
	| UC    | teamlapen-lib         | 1.5.0-alpha+03-09-16-16 | Vampirism-1.12.2-1.5.0-alpha+03-09-16-16.jar      | None                                     |
	| UC    | waystones             | 4.0.67                  | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| UC    | wizardry              | 0.9.9                   | wizardry-0.9.9.jar                                | None                                     |
	| UC    | worldedit             | 6.1.10-SNAPSHOT         | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| UC    | llibrary              | 1.7.14                  | llibrary-1.7.14-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | librarianliblate      | 4.15                    | librarianlib-1.12.2-4.15.jar                      | None                                     |

	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Wizardry Plugin (wizardry-0.9.9.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.180.513' Renderer: 'AMD Radeon(TM) R2 Graphics'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

**Comment by MineRobber9000** [comment]
Known issue. Delete your old config. (`config/codechicken.cfg` IIRC)

**Comment by Idkyet124** [comment]
How do i delete my old config? Sorry just don't know anything lmao

**Comment by MineRobber9000** [comment]
Go to the "config" folder where you installed the mods and put the file named "codechicken.cfg" in the recycle bin/trash/whatever your OS calls it
