### ISSUE TITLE
Block rendering error - trying to understand the cause.

### ISSUE THREAD

**Issue by tomdodd4598** [TheCBProject/CodeChickenLib#228]
Hey there!

Recently I had a [bug report](https://github.com/turbodiesel4598/NuclearCraft/issues/469) showing that the render dispatcher is [throwing errors](https://pastebin.com/kX3GxgDy) related to one of my fluid blocks in the NuclearCraft mod.

My question is simply what I need to do on NC's side to prevent this, if anything. I don't really understand why the error is being thrown in the fist place.

Thanks in advance!

**Comment by covers1624** [comment]
```
Caused by: java.lang.IllegalArgumentException: Cannot set unlisted property net.minecraftforge.common.property.PropertyFloat@242b8228 to NaN on block nuclearcraft:fluid_nak, it is not an allowed value
    at net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.withProperty(ExtendedBlockState.java:117) ~[ExtendedBlockState$ExtendedStateImplementation.class:?]
    at net.minecraftforge.fluids.BlockFluidBase.getExtendedState(BlockFluidBase.java:528) ~[BlockFluidBase.class:?]
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79) ~[bvm.class:?]
```
Apparently your fluid block is setting a NaN UnlistedProperty.

**Comment by tomdodd4598** [comment]
Right, but I'm not adding any more properties to the block than the standard BlockFluidBase class does, so is there something I'm doing wrong on my side or is this error thrown occasionally by vanilla or other fluid blocks?
