### ISSUE TITLE
minecraft crashes because of nei and codechickenlib.

### ISSUE THREAD

**Issue by bugreporter12** [TheCBProject/CodeChickenLib#233]
when i use the latest or a bit older versions of nei or codechicken it always crashes on 1.12.2 it only works on 1.7.10 for me and here is the crash report
now these crash reports are a year old but there the same as the ones from today

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Regeneration Sound Handler (Regeneration-1.12.2-1.5.0.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.1.jar)
  TickrateChanger (TickrateChanger-1.0.14.jar)
  Techguns Core (Techguns-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 4/21/19 11:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:61)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:67)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 473176448 bytes (451 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2770 Optifine OptiFine_1.12.2_HD_U_E1 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID              | Version      | Source                                         | Signature                                |
	|:------- |:--------------- |:------------ |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft       | 1.12.2       | minecraft.jar                                  | None                                     |
	| UCHIJA  | mcp             | 9.42         | minecraft.jar                                  | None                                     |
	| UCHIJA  | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2770.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge           | 14.23.5.2770 | forge-1.12.2-14.23.5.2770.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | techguns_core   | 1.12.2-1.0   | minecraft.jar                                  | None                                     |
	| UCHIJA  | tammodized      | 0.15.5       | TamModized-1.12.1-0.15.5.jar                   | None                                     |
	| UCHIJA  | aov             | 0.8.14       | AoV-1.12-0.8.14.jar                            | None                                     |
	| UCHIJA  | autoreglib      | 1.3-26       | AutoRegLib-1.3-26.jar                          | None                                     |
	| UCHIJA  | gorecore        | 1.12.2-0.4.5 | avatarmod-1.5.9.3.jar                          | None                                     |
	| UCHIJA  | avatarmod       | unspecified  | avatarmod-1.5.9.3.jar                          | None                                     |
	| UCHIJA  | codechickenlib  | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | cosmicnpcs      | 1.2.1        | CosmicNPCs-1.2.1-mc1.12.2.jar                  | None                                     |
	| UCHIJA  | crafttweaker    | 4.1.2        | CraftTweaker2-1.12-4.1.2.jar                   | None                                     |
	| UCHIJA  | ctgui           | 1.0.0        | CraftTweaker2-1.12-4.1.2.jar                   | None                                     |
	| UCHIJA  | jei             | 4.15.0.269   | jei_1.12.2-4.15.0.269.jar                      | None                                     |
	| UCHIJA  | crafttweakerjei | 2.0.0        | CraftTweaker2-1.12-4.1.2.jar                   | None                                     |
	| UCHIJA  | cyclopscore     | 0.11.11      | CyclopsCore-1.12.2-0.11.11.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA  | ebwizardry      | 4.1.2        | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar | None                                     |
	| UCHIJA  | lucraftcore     | 1.12.2-2.4.1 | LucraftCore-1.12.2-2.4.1.jar                   | None                                     |
	| UCHIJA  | heroesexpansion | 1.12.2-1.3.2 | HeroesExpansion-1.12.2-1.3.2.jar               | None                                     |
	| UCHIJA  | iblis           | 0.4.14       | iblis-0.4.14.jar                               | None                                     |
	| UCHIJA  | kagic           | X10          | kagic-X10.jar                                  | None                                     |
	| UCHIJA  | lootbags        | 2.5.1        | LootBags-Mod-1.12.2.jar                        | None                                     |
	| UCHIJA  | loottweaker     | 0.0.6.5      | LootTweaker-1.12.2.jar                         | None                                     |
	| UCHIJA  | lordcraft       | 1.0.0        | Lord+Craft+2.9.14.jar                          | None                                     |
	| UCHIJA  | radixcore       | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar           | None                                     |
	| UCHIJA  | mca             | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar                 | None                                     |
	| UCHIJA  | mclib           | 1.0          | mclib-1.0-1.12.2.jar                           | None                                     |
	| UCHIJA  | mjrlegendslib   | 1.12.2-1.1.6 | MJRLegendsLib-1.12.2-1.1.6.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA  | mmm             | 1.0.8        | mutatedmobs-1.0.8.jar                          | None                                     |
	| UCHIJA  | notenoughwands  | 1.5.9        | Not-Enough-Wands-Mod-1.12.1.jar                | None                                     |
	| UCHIJEE | nei             | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ   | subcommonlib    | 1.2.0.1      | subcommonlib-sublib-1.12.2-1.2.0.4.jar         | None                                     |
	| UCHIJ   | petbuddy        | $version     | petbuddy-petbuddy-1.12.2-2.4.0.1.jar           | None                                     |
	| UCHIJ   | regeneration    | 1.5.0        | Regeneration-1.12.2-1.5.0.jar                  | None                                     |
	| UCHIJ   | roughmobs       | 1.0          | Rough-Mobs-Mod-1.12.1.jar                      | None                                     |
	| UCHIJ   | silentlib       | 3.0.9        | SilentLib-1.12.2-3.0.9-159.jar                 | None                                     |
	| UCHIJ   | scalinghealth   | 1.3.31       | ScalingHealth-1.12.2-1.3.31-132.jar            | None                                     |
	| UCHIJ   | structpro       | 4.0          | Structpro-1.12.2.jar                           | None                                     |
	| UCHIJ   | techguns        | 2.0.1.0      | Techguns-Mod-1.12.2.jar                        | None                                     |
	| UCHIJ   | tickratechanger | 1.0.14       | TickrateChanger-1.0.14.jar                     | None                                     |
	| UCHIJ   | torohealthmod   | 1.12.2-11    | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar    | None                                     |
	| UCHIJ   | uncraftingtable | 1.8-beta6    | Uncrafting-Table-Mod-1.12.1.jar                | None                                     |

	Loaded coremods (and transformers): 
Regeneration Sound Handler (Regeneration-1.12.2-1.5.0.jar)
  me.suff.regeneration.client.sound.echo.RegenClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.1.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
Techguns Core (Techguns-Mod-1.12.2.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics'
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by Rumaruka** [comment]
Update Forge

**Comment by covers1624** [comment]
Works fine for me, Either NEI's AccessTransformer isnt running because of coremods, or you need to update forge.
