### ISSUE TITLE
CCL Common Crash

### ISSUE THREAD

**Issue by policeMarcus** [TheCBProject/CodeChickenLib#236]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 5/10/19 1:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 358431856 bytes (341 MB) / 939524096 bytes (896 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version               | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                         | 1.12.2                | minecraft.jar                                      | None                                     |
	| UCH   | mcp                               | 9.42                  | minecraft.jar                                      | None                                     |
	| UCH   | FML                               | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                             | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore                      | 0.12.2                | minecraft.jar                                      | None                                     |
	| UCH   | ate                               | 1.0.0                 | ATE-1.5.jar                                        | None                                     |
	| UCEE  | codechickenlib                    | 3.2.2.353             | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux                      | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | brandonscore                      | 2.4.10                | BrandonsCore-1.12.2-2.4.10.198-universal.jar       | None                                     |
	| UC    | buildcraftlib                     | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftcore                    | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftbuilders                | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcrafttransport               | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftsilicon                 | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftcompat                  | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftenergy                  | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftfactory                 | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | buildcraftrobotics                | 7.99.24.1             | buildcraft-all-7.99.24.1.jar                       | None                                     |
	| UC    | customnpcs                        | 1.12                  | CustomNPCs_1.12.2(30Jan19).jar                     | None                                     |
	| UC    | ptrmodellib                       | 1.0.4                 | PTRLib-1.0.4.jar                                   | None                                     |
	| UC    | props                             | 2.6.2                 | Decocraft-2.6.2_1.12.2.jar                         | None                                     |
	| UC    | draconicevolution                 | 2.3.21                | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar | None                                     |
	| UC    | endercore                         | 1.12.2-0.5.57         | EnderCore-1.12.2-0.5.57.jar                        | None                                     |
	| UC    | enderio                           | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderiointegrationtic             | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderiobase                       | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderioconduits                   | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderioconduitsappliedenergistics | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderioconduitsopencomputers      | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderioconduitsrefinedstorage     | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderiointegrationforestry        | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderiointegrationticlate         | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | ftblib                            | 5.4.1.98              | FTBLib-5.4.1.98.jar                                | None                                     |
	| UC    | enderiomachines                   | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | enderiopowertools                 | 5.0.44                | EnderIO-1.12.2-5.0.44.jar                          | None                                     |
	| UC    | explosions                        | 1.0.0                 | ExplosionsPlusPlusPlus_1.0.0_1.12.2.jar            | None                                     |
	| UC    | ftbutilities                      | 5.4.0.96              | FTBUtilities-5.4.0.96.jar                          | None                                     |
	| UC    | ghostsexplosives                  | 2.3.0 - MC 1.12.2     | Ghost's+Explosives+2.3.0+-+MC1.12.2.jar            | None                                     |
	| UC    | waila                             | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| UC    | igauntlet                         | 3.5                   | IGauntlet-1.12.2-3.5.jar                           | None                                     |
	| UC    | journeymap                        | 1.12.2-5.5.5b5        | journeymap-1.12.2-5.5.5b5.jar                      | None                                     |
	| UC    | malisiscore                       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| UC    | malisisdoors                      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| UC    | mantle                            | 1.12-1.3.3.49         | Mantle-1.12-1.3.3.49.jar                           | None                                     |
	| UC    | mw                                | 1.11.7.7              | mw-1.11.7.7_mc1.12.2.jar                           | None                                     |
	| UC    | nuclearcraft                      | 2.16e                 | NuclearCraft-2.16e-1.12.2.jar                      | None                                     |
	| UC    | openmods                          | 0.12.2                | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks                        | 1.8.1                 | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | oreexcavation                     | 1.4.140               | OreExcavation-1.4.140.jar                          | None                                     |
	| UC    | scpsarmor                         | 1.0.0                 | SCP's+Armor.jar                                    | None                                     |
	| UC    | scp_lockdown_extras               | 0.1                   | SCP+Lockdown+Heavy+Expansion+0.5.2.jar             | None                                     |
	| UC    | scp                               | 2.1.1                 | SCP+Lockdown-1.12.2-2.1.1-beta.jar                 | None                                     |
	| UC    | scpextras                         | 0.5                   | SCPAeywoosExtrasv0.5.jar                           | None                                     |
	| UC    | scple                             | 1.0                   | scple-1.0.jar                                      | None                                     |
	| UC    | worldedit                         | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar  | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]

I do not have the mods in a onedrive or anything, I just downloaded forge and the mods and this crash happen. Doesn't seem anyone has found a fix to similiar issues.

**Comment by policeMarcus** [comment]
Fixed! Instructions below:

1. Search %appData% in Windows "Search"
2. Click .minecraft
3. Go into the config folder.
4. Remove any codechicken related configs.
5. Restart minecraft.
