### ISSUE TITLE
World is owned by 'Server thread' (ID: 125), but was accessed from thread 'Client thread' (ID: 1)

### ISSUE THREAD

**Issue by Insane96** [TheCBProject/CodeChickenLib#237]
```
[10:31:01] [Client thread/WARN] [Phosphor]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!
This is *bad practice* and can cause severe issues in your game. Phosphor has done as best as it can to mitigate this violation, but it may negatively impact performance or introduce stalls.
In a future release, this violation may result in a hard crash instead of the current soft warning. You should report this issue to our issue tracker with the following stacktrace information.
(If you are aware you have misbehaving mods and cannot resolve this issue, you can safely disable this warning by setting `enable_illegal_thread_access_warnings` to `false` in Phosphor's configuration file for the time being.)
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 125), but was accessed from thread 'Client thread' (ID: 1)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.acquireLock(LightingEngine.java:204) [LightingEngine.class:?]
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:185) [LightingEngine.class:?]
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:1789) [axw.class:?]
	at net.minecraft.world.World.func_175705_a(World.java:836) [amu.class:?]
	at net.minecraft.world.World.func_175626_b(World.java:887) [amu.class:?]
	at net.minecraft.client.particle.Particle.func_189214_a(Particle.java:344) [btf.class:?]
	at codechicken.lib.render.particle.DigIconParticle.func_180434_a(DigIconParticle.java:70) [DigIconParticle.class:?]
	at net.minecraft.client.particle.ParticleManager.func_78874_a(ParticleManager.java:325) [btg.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1387) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by covers1624** [comment]
The only places i use DigIconParticle i absolutely use the Client world. Another mod is using DigIconParticle incorrectly and unfortunately its almost impossible to track this down. Sorry.
