### ISSUE TITLE
code chicken lib caught an exception

### ISSUE THREAD

**Issue by Azonerath** [TheCBProject/CodeChickenLib#240]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/19/19 8:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 708103936 bytes (675 MB) / 1543503872 bytes (1472 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2837 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                           | Signature                                |
	|:----- |:-------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCH   | mcp                  | 9.42              | minecraft.jar                                    | None                                     |
	| LCH   | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2837.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2837      | forge-1.12.2-14.23.5.2837.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | techguns_core        | 1.12.2-1.0        | minecraft.jar                                    | None                                     |
	| LCH   | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | bibliocraft          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCH   | botania              | r1.10-361         | Botania+r1.10-361.jar                            | None                                     |
	| LCH   | buildcraftlib        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftcore       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftbuilders   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcrafttransport  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftsilicon    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftcompat     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftenergy     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftfactory    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | buildcraftrobotics   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                     | None                                     |
	| LCH   | cdm                  | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
	| LCH   | cfm                  | 6.2.1             | cfm-6.2.1-mc1.12.2.jar                           | None                                     |
	| LCE   | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore             | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar           | None                                     |
	| LC    | cofhworld            | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | valkyrielib          | 1.12.2-2.0.20.1   | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
	| LC    | environmentaltech    | 1.12.2-2.0.20.1   | environmentaltech-1.12.2-2.0.20.1.jar            | None                                     |
	| LC    | forgelin             | 1.8.2             | Forgelin-1.8.2.jar                               | None                                     |
	| LC    | llibrary             | 1.7.17            | llibrary-1.7.17-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | fossil               | 8.0.0             | fossilsarcheology-8.0.0.jar                      | None                                     |
	| LC    | fp                   | 26.4.75           | Futurepack-1.12.2-26.4.75.jar                    | a8cfb0576c44b2711002b9e45850732f0b8c7cb6 |
	| LC    | fp.api               | 1.1.0             | Futurepack-1.12.2-26.4.75.jar                    | None                                     |
	| LC    | ichunutil            | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | gravitygun           | 7.0.0             | GravityGun-1.12.2-7.0.1.jar                      | None                                     |
	| LC    | ic2                  | 2.8.153-ex112     | industrialcraft-2-2.8.153-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | railcraft            | 12.0.0            | railcraft-12.0.0.jar                             | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | mantle               | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                         | None                                     |
	| LC    | tconstruct           | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar                 | None                                     |
	| LC    | thermalfoundation    | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | immersiveengineering | 0.12-89           | ImmersiveEngineering-0.12-89.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | immersivecables      | 1.3.2             | ImmersiveCables-1.12.2-1.3.2.jar                 | None                                     |
	| LC    | trackapi             | 1.1               | TrackAPI-1.1_1.12.jar                            | None                                     |
	| LC    | immersiverailroading | 1.6.1             | ImmersiveRailroading-1.6.1_1.12-1138.jar         | None                                     |
	| LC    | immersivetech        | 1.3.10            | immersivetech-1.12-1.3.10.jar                    | None                                     |
	| LC    | magneticraft         | 2.5.2             | Magneticraft_1.12-2.5.2-dev.jar                  | None                                     |
	| LC    | mekanism             | 1.12.2-9.7.4.375  | Mekanism-1.12.2-9.7.4.375.jar                    | None                                     |
	| LC    | minestuck            | 1.12.2-1.4.287    | Minestuck-1.12.2-1.4.287.jar                     | None                                     |
	| LC    | modelloader          | 1.1.5             | modelloader-1.1.5.jar                            | None                                     |
	| LC    | portalgun            | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | row                  | 1.12.2-1901-9p1   | RailsOfWar-1.12.2-1901-9p1.jar                   | None                                     |
	| LC    | reborncore           | 3.13.12.447       | RebornCore-1.12.2-3.13.12.447-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | thermalexpansion     | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | redstonearsenal      | 2.6.2             | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | techguns             | 2.0.1.2           | techguns-1.12.2-2.0.1.2_1.jar                    | None                                     |
	| LC    | techreborn           | 2.22.1.979        | TechReborn-1.12.2-2.22.1.979-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | thermalcultivation   | 0.3.2             | ThermalCultivation-1.12.2-0.3.2.11-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics      | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalinnovation    | 0.3.2             | ThermalInnovation-1.12.2-0.3.2.11-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | tcomplement          | ${version}        | TinkersComplement-1.12.2-0.3.2.jar               | None                                     |
	| LC    | universalmodifiers   | 1.12.2-1.0.16.1   | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
	| LC    | techreborn_compat    | 1.0.0             | TechReborn-ModCompatibility-1.12.2-1.1.0.38.jar  | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Techguns Core (techguns-1.12.2-2.0.1.2_1.jar)
  techguns.core.TechgunsASMTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13543 Compatibility Profile Context 25.20.15003.5010' Renderer: 'Radeon RX 580 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)

**Comment by Azonerath** [comment]
fixed by deleting the old codechicken___.cfg files
