### ISSUE TITLE
Game keeps crashing, I dont know why

### ISSUE THREAD

**Issue by deathshadow137** [TheCBProject/CodeChickenLib#243]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ClientCommandsLoadingPlugin (clientcommands-1.12-20190126-snapshot (1).jar)
  ForgeHaxCoreMod (forgehax-1.12.2-2.9.0.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/17/19 4:47 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1426485336 bytes (1360 MB) / 1946157056 bytes (1856 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2816 Optifine OptiFine_1.12.2_HD_U_E3 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version                | Source                                        | Signature                                |
	|:----- |:-------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft      | 1.12.2                 | minecraft.jar                                 | None                                     |
	| LCH   | mcp            | 9.42                   | minecraft.jar                                 | None                                     |
	| LCH   | FML            | 8.0.99.99              | forge-1.12.2-14.23.5.2816.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge          | 14.23.5.2816           | forge-1.12.2-14.23.5.2816.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | clientcommands | 1.12-20190126-snapshot | clientcommands-1.12-20190126-snapshot (1).jar | None                                     |
	| LCE   | codechickenlib | 3.2.2.352              | CodeChickenLib-1.12.2-3.2.2.352-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | forgehax       | 2.9.0                  | forgehax-1.12.2-2.9.0.jar                     | None                                     |
	| LC    | pixelmon       | 7.0.6                  | Pixelmon-1.12.2-7.0.6-universal.jar           | None                                     |
	| LC    | gameshark      | 5.2.1                  | gameshark-1.12.2-5.2.1-universal.jar          | None                                     |
	| LC    | jei            | 4.15.0.279             | jei_1.12.2-4.15.0.279.jar                     | None                                     |
	| LC    | nei            | 2.4.2                  | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | orelib         | 3.5.2.2                | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
ClientCommandsLoadingPlugin (clientcommands-1.12-20190126-snapshot (1).jar)
  net.earthcomputer.clientcommands.core.ProxyTransformer
  net.earthcomputer.clientcommands.core.NetHandlerTransformer
  net.earthcomputer.clientcommands.core.IntegratedServerRaceFixTransformer
  net.earthcomputer.clientcommands.core.RenderManagerTransformer
ForgeHaxCoreMod (forgehax-1.12.2-2.9.0.jar)
  com.matt.forgehax.asm.ForgeHaxTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11627 Compatibility Profile Context' Renderer: 'AMD Radeon HD 6450'

**Comment by Rumaruka** [comment]
**ConfigFile$ConfigException:** 
Try delete config file =)

**Comment by ItamarEdri** [comment]
> **ConfigFile$ConfigException:**
> Try delete config file =)

Where do I delete it from?

**Comment by Rumaruka** [comment]
in folder "config" your modpack

**Comment by MineRobber9000** [comment]
Delete the `config/codechicken.cfg` file in your .minecraft folder (or wherever your modpack's info is stored). It's your config file, and it's from an old version that uses a type that the new config parser doesn't recognize.
