### ISSUE TITLE
My codechickenlib is crashing

### ISSUE THREAD

**Issue by Doo-dy** [TheCBProject/CodeChickenLib#249]
So the issue is that i really need codechickenlib for two of the thermal of the three thermal mods (thermal dynamics, thermal foundation, thermal expansion), i've tried to fix it but it didn't work at all so could you please help me? Here's the problem 
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2019-07-23 10:57:55 CEST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
    at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
    at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
    at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
    at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
    at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
    ... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 443584928 bytes (423 MB) / 973078528 bytes (928 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2831 34 mods loaded, 34 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version               | Source                                              | Signature                                |
       |:----- |:-------------------- |:--------------------- |:--------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft            | 1.12.2                | minecraft.jar                                       | None                                     |
       | LCH   | mcp                  | 9.42                  | minecraft.jar                                       | None                                     |
       | LCH   | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2831.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                | 14.23.5.2831          | forge-1.12.2-14.23.5.2831.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | obfuscate            | 0.2.6                 | minecraft.jar                                       | None                                     |
       | LCH   | techguns_core        | 1.12.2-1.0            | minecraft.jar                                       | None                                     |
       | LCH   | securitycraft        | v1.8.12               | 1.12.2SecurityCraftv1.8.12 (1).jar                  | None                                     |
       | LCH   | jei                  | 4.15.0.268            | jei_1.12.2-4.15.0.268 (1).jar                       | None                                     |
       | LCH   | quark                | r1.5-164              | Quark-r1.5-164.jar                                  | None                                     |
       | LCH   | autoreglib           | 1.3-30                | AutoRegLib-1.3-30_1.jar                             | None                                     |
       | LCH   | backpack             | 3.0.2                 | backpack-3.0.2-1.12.2.jar                           | None                                     |
       | LCH   | ctm                  | MC1.12.2-0.3.3.22     | Connected-Textures-Mod-1.12.2.jar                   | None                                     |
       | LCH   | chisel               | MC1.12.2-0.2.0.31     | Chisel-Mod-1.12.2.jar                               | None                                     |
       | LCE   | codechickenlib       | 3.2.2.353             | CodeChickenLib-1.12.2-3.2.2.353-universal (1).jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | redstoneflux         | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal (2).jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | cofhcore             | 4.6.3                 | CoFHCore-1.12.2-4.6.3.27-universal (2).jar          | None                                     |
       | LC    | cofhworld            | 1.3.1                 | CoFHWorld-1.12.2-1.3.1.7-universal (1).jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | cdm                  | 0.4.1                 | device-mod-0.4.1-1.12.2_1.jar                       | None                                     |
       | LC    | foamflower           | 1.12.2-1.0.0.0-beta1  | foamflower-1.12.2-1.0.0.0-beta1_2.jar               | None                                     |
       | LC    | enderpay             | 1.12.2-1.0.1.0        | enderpay-1.12.2-1.0.1.0_1.jar                       | None                                     |
       | LC    | cfm                  | 6.3.0                 | furniture-6.3.0-1.12.2_1.jar                        | None                                     |
       | LC    | cgm                  | 0.12.1                | guns-0.12.1-1.12.2.jar                              | None                                     |
       | LC    | ic2                  | 2.8.169-ex112         | industrialcraft-2-2.8.169-ex112 (1).jar             | de041f9f6187debbc77034a344134053277aa3b0 |
       | LC    | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1_1 (1).jar                  | None                                     |
       | LC    | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0_1.jar                     | None                                     |
       | LC    | harvestcraft         | 1.12.2zb              | PamsHarvestCraft1.12.2zdSurpriseforYogcast.jar      | None                                     |
       | LC    | techguns             | 2.0.2.0               | techguns-1.12.2-2.0.2.0_pre3.1 (2).jar              | None                                     |
       | LC    | thermalfoundation    | 2.6.3                 | ThermalFoundation-1.12.2-2.6.3.27-universal (1).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | thermalexpansion     | 5.5.4                 | ThermalExpansion-1.12.2-5.5.4.43-universal (1).jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | thermaldynamics      | 2.5.5                 | ThermalDynamics-1.12.2-2.5.5.21-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LC    | vanillafix           | 1.0.10-SNAPSHOT       | VanillaFix-1.0.10-99 (1).jar                        | None                                     |
       | LC    | vehicle              | 0.41.0                | vehicle-mod-0.41.0-1.12.2.jar                       | None                                     |
       | LC    | vending              | 1.12.2-3.0.1.2        | vending-1.12.2-3.0.1.2_1.jar                        | None                                     |
       | LC    | immersiveengineering | 0.12-89               | ImmersiveEngineering-0.12-89 (1).jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
  Loaded coremods (and transformers): IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      CTMCorePlugin (Connected-Textures-Mod-1.12.2.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99 (1).jar)
                                        
                                      Quark Plugin (Quark-r1.5-164.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2_1.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1_1 (1).jar)
                                        
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1 (2).jar)
                                        techguns.core.TechgunsASMTransformer
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 530'
  Suspected Mods: CodeChicken Lib (codechickenlib)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2831
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 530 GL version 4.5.0 - Build 22.20.16.4749, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (United Kingdom)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by gigabit101** [comment]
delete your CCL config file and start the game again

**Comment by Doo-dy** [comment]
i already tried but it didn't worked
