### ISSUE TITLE
java.lang.SecurityException: class "codechicken.lib.util.FuelUtils"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by Ezoteric** [TheCBProject/CodeChickenLib#25]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (CodeChickenLib)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/util/FuelUtils
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.util.FuelUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.SecurityException: class "codechicken.lib.util.FuelUtils"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

-----------------
forge:1.10.2-2185
chicken mod versions:
ChickenChunks {2.2.0.52}
CodeChickenLib 2.5.0.178
CodeChickenCore{2.4.0.100}
EnderStorage{2.2.0.95}

**Comment by covers1624** [comment]
Do you have an old version of CCL insalled in /mods/1.10.2?

**Comment by covers1624** [comment]
Closed due to not enough information to look in to for issues. This crash is due to the jar signing i recently implemented. This specific issue will only occur if someone has a duplicated jar. Check your /mods/1.10.2 folder for ANY ccl versions, if one is found in that folder remove it. Make sure the latest CCL from curse is installed in ONLY the /mods/ folder.

**Comment by Cylindric** [comment]
I'm getting the same thing when trying to update the FTB DireWolf20 pack with some new versions of the various mods.

I haven't yet tried removing mods to simplify the list, but thought I'd let you know what I have now before I start digging.

```
ActuallyAdditions-1.10.2-r90.jar
AkashicTome-1.0-5.jar
appliedenergistics2-rv4-alpha-8.jar
AutoRegLib-1.0-2.jar
Bagginses-1.10.2-3.0.4g.jar
Baubles-1.10.2-1.3.6.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar
BloodMagic-1.9.4-2.1.0-68.jar
Bookshelf-1.10.2-1.4.3.338.jar
Botania r1.9-339.jar
BrandonsCore-1.10.2-2.1.1.61-universal.jar
Chameleon-1.10-2.2.0.jar
Chisel-MC1.10.2-0.0.7.7.jar
chiselsandbits-12.7.jar
CodeChickenCore-1.10.2-2.4.0.100-universal.jar
CodeChickenLib-1.10.2-2.5.0.178-universal.jar
CompactSolars-1.10.2-5.0.5.329-universal.jar
CraftTweaker-1.10.2-3.0.15.jar
DarkUtilities-1.10.2-1.1.6.99.jar
deepresonance-1.10-1.3.1.jar
Draconic-Evolution-1.10.2-2.0.3.137-universal.jar
ElecCore-1.10.2-1.6.345.jar
EnderCore-1.10.2-0.4.1.60-beta.jar
EnderIO-1.10.2-3.0.1.144_beta.jar
extrautils2-1.10.2-1.1.2.jar
ExtremeReactors-1.10.2-0.4.5.21.jar
FastLeafDecay-v11.jar
flatcoloredblocks-mc1.10-v4.4.jar
forestry_1.10.2-5.2.16.331.jar
FTBLib-1.10.2-3.1.5.jar
FTBUtilities-1.10.2-3.1.4.jar
GraveStone Mod 1.5.9.jar
Guide-API-1.10.2-2.0.2-45.jar
ImmersiveEngineering-0.10-53.jar
industrialcraft-2-2.6.105-ex110.jar
inventorysorter-1.10-0.10.0+42.jar
IronBackpacks-1.10.2-2.2.19.jar
ironchest-1.10.2-7.0.11.797.jar
jei_1.10.2-3.13.6.387.jar
jeibees-0.9.0.4-mc1.10.2.jar
journeymap-1.10.2-5.3.2.jar
JustEnoughResources-1.10.2-0.5.8.98.jar
LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar
Mantle-1.10.2-1.1.2.jar
mcjtylib-1.10-2.2.0.jar
MCMultiPart-1.3.0-universal.jar
Mercurius-1.10.2-1.0.2.jar
Morpheus-1.10.2-3.1.12.jar
Morph-o-Tool-1.0-12.jar
notenoughwands-1.10-1.4.0.jar
OpenComputers-MC1.10.2-1.6.1.6.jar
Psi-r1.0-42.jar
Quark-r1.0-60.jar
Railcraft_1.10.2-10.0.1.jar
rangedpumps-0.3.jar
refinedstorage-1.2.8.jar
rftools-1.10-5.62.jar
rftoolsctrl-1.10-1.5.2.jar
rftoolsdim-1.10-4.45.jar
StorageDrawers-1.10.2-3.5.14.jar
SuperCircuitMaker-1.0.4.jar
TConstruct-1.10.2-2.5.6b.jar
theoneprobe-1.10-1.3.3.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10.2-1.1.9.jar
Wawla-1.10.2-2.3.1.213.jar
zerocore-1.10.2-0.0.8.2.jar
```

I am using forge-1.10.2-12.18.3.2185-universal.jar

I have nothing in mods/1.10.2 at all.

**Comment by covers1624** [comment]
Update brandons core.

**Comment by Cylindric** [comment]
Perfect, thank you!
