### ISSUE TITLE
problems loading in mods

### ISSUE THREAD

**Issue by hellReaser** [TheCBProject/CodeChickenLib#253]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 8/6/19 11:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Roots (roots)
Caused by: java.lang.NoClassDefFoundError: epicsquid/roots/capability/runic_shears/RunicShearsCapability
	at epicsquid.roots.Roots.preInit(Roots.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: epicsquid.roots.capability.runic_shears.RunicShearsCapability
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: epicsquid/mysticallib/capability/EntityCooldownCapability
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: epicsquid.mysticallib.capability.EntityCooldownCapability
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 648200216 bytes (618 MB) / 1644167168 bytes (1568 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                            | Signature                                |
	|:----- |:-------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCH   | mcp                  | 9.42              | minecraft.jar                                     | None                                     |
	| LCH   | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2836.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2836      | forge-1.12.2-14.23.5.2836.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore        |                   | minecraft.jar                                     | None                                     |
	| LCH   | obfuscate            | 0.2.6             | minecraft.jar                                     | None                                     |
	| LCH   | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                         | None                                     |
	| LCH   | abyssalcraft         | 1.9.10            | AbyssalCraft-1.12.2-1.9.10.jar                    | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | actuallyadditions    | 1.12.2-r149       | ActuallyAdditions-1.12.2-r149.jar                 | None                                     |
	| LCH   | orbis-lib            | 0.2.0             | orbis-lib-1.12.2-0.2.0+build74.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether               | 0.2.1             | Aether-2-Mod-1.12.2.jar                           | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | appliedenergistics2  | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCH   | atum                 | 2.0.12            | Atum-1.12.2-2.0.12.jar                            | None                                     |
	| LCH   | biometweaker         | 3.2.354           | BiomeTweaker-Mod-1.12.2.jar                       | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
	| LCH   | guideapi             | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| LCH   | bloodmagic           | 1.12.2-2.4.1-103  | BloodMagic-1.12.2-2.4.1-103.jar                   | None                                     |
	| LCH   | bookshelf            | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | botania              | r1.10-361         | Botania+r1.10-361.jar                             | None                                     |
	| LCH   | codechickenlib       | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal (2).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chickenchunks        | 2.4.2.74          | ChickenChunks-1.12.2-2.4.2.74-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore             | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LCH   | cofhworld            | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | desertcraft          | 1.12.2a           | Desert-Craft-Mod-1.12.2.jar                       | None                                     |
	| LCH   | embers               | 0.230             | Embers-Mod-1.12.2.jar                             | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCH   | twilightforest       | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
	| LCH   | extrautils2          | 1.0               | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCH   | zerocore             | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                       | None                                     |
	| LCH   | bigreactors          | 1.12.2-0.4.5.67   | ExtremeReactors-1.12.2-0.4.5.67.jar               | None                                     |
	| LCH   | galacticraftcore     | 4.0.2.211         | GalacticraftCore-1.12.2-4.0.2.211.jar             | None                                     |
	| LCH   | galacticraftplanets  | 4.0.2.211         | Galacticraft-Planets-1.12.2-4.0.2.211.jar         | None                                     |
	| LCH   | grapplemod           | 1.12.2-v11.1      | grapplemod-v11.1-1.12.2.jar                       | None                                     |
	| LCH   | cgm                  | 0.12.2            | guns-0.12.2-1.12.2.jar                            | None                                     |
	| LCH   | huntingdim           | 1.0.39            | HuntingDimension-1.12.2-1.0.39.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | thermalfoundation    | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | immersiveengineering | 0.12-89           | ImmersiveEngineering-0.12-89.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | immersivetech        | 1.3.10            | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| LCH   | mjrlegendslib        | 1.12.2-1.1.8      | MJRLegendsLib-1.12.2-1.1.8.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCE   | roots                | 1.12.2-3.0.4      | Roots-1.12.2-3.0.4.jar                            | None                                     |
	| LC    | mysticalworld        | 1.12.2-1.3.2      | MysticWorld-1.12.2-1.3.2.jar                      | None                                     |
	| LC    | nei                  | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | nuclearcraft         | 2.17c             | NuclearCraft-2.17c-1.12.2.jar                     | None                                     |
	| LC    | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2ze.jar                   | None                                     |
	| LC    | patchouli            | 1.0-20            | Patchouli-1.0-20.jar                              | None                                     |
	| LC    | projecte             | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                       | None                                     |
	| LC    | pvj                  | 1.6.3             | ProjectVibrantJourneys-1.12.2-1.6.3.jar           | None                                     |
	| LC    | xreliquary           | 1.12.2-1.3.4.786  | Reliquary-1.12.2-1.3.4.786.jar                    | None                                     |
	| LC    | ropebridge           | 2.0.5             | ropebridge-1.12-2.0.7.jar                         | None                                     |
	| LC    | thermaldynamics      | 2.5.5             | ThermalDynamics-1.12.2-2.5.5.21-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | tinymobfarm          | 1.0.5             | TinyMobFarm-1.12.2-1.0.5.jar                      | None                                     |
	| LC    | phosphor-lighting    | 1.12.2-0.2.4      | phosphor-1.12.2-0.2.4+build46.jar                 | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LC    | mysticallib          | 1.12.2-1.2.1      | MysticalLib-1.12.2.jar                            | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

**Comment by covers1624** [comment]
This is clearly not an issue with CCL. Roots threw an error loading.
