### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

### ISSUE THREAD

**Issue by JakeOfAuthority99** [TheCBProject/CodeChickenLib#273]
I loaded up my version of Minecraft (forge 1.12.2-forget1.12.2-14.23.5.2847) and ran into this problem with CCL. I continued to do some research and found a post related to this issue and found a comment saying to delete the config instance of CCL. I continued to delete the instance and then tried loading it up again but I was given the same error message. Any suggestions or help would be great.

ENTIRE CRASH REPORT:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/26/19 12:33 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 416732568 bytes (397 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                  | Source                                    | Signature                                |
	|:----- |:--------------- |:------------------------ |:----------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2                   | minecraft.jar                             | None                                     |
	| LCH   | mcp             | 9.42                     | minecraft.jar                             | None                                     |
	| LCH   | FML             | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCH   | forge           | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar             | None                                     |
	| LCH   | ctm             | MC1.12.2-1.0.1.30        | CTM-MC1.12.2-1.0.1.30.jar                 | None                                     |
	| LCH   | jei             | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                 | None                                     |
	| LCH   | chisel          | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar              | None                                     |
	| LCE   | codechickenlib  | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-deobf.jar | None                                     |
	| LC    | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | journeymap      | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar               | None                                     |
	| LC    | nei             | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-deobf.jar | None                                     |
	| LC    | ropebridge      | 2.0.5                    | ropebridge-1.12-2.0.7.jar                 | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 630'

**Comment by LXGaming** [comment]
You're attempting to use `deobf` versions of CCL and NEI, these files are for developers only.

You need to download the `universal` versions of CCL and NEI.
