### ISSUE TITLE
someone wrote flase on line 18

### ISSUE THREAD

**Issue by d3rpp** [TheCBProject/CodeChickenLib#275]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid Boolean qualifier! flase on line: 18, supported: true, 1, yes, false, 0, no
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)

I Cloned this repo to try opening it, idk whats wrong

**Comment by d3rpp** [comment]
I Found the problem in the .cfg file mentioned in the previous problem and fixed it, now am getting a different error
`Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)`

i have no clue what this means

**Comment by covers1624** [comment]
Hi, Your second issue there, you're using the `deobf` version of CCL, you need the `universal` version.
As to the original post, seems like a bug, there might be a trailing space, try deleting the line in the config file and letting it re-generate it and change the value again.

**Comment by d3rpp** [comment]
Thankyou, I will try this later

:-)
