### ISSUE TITLE
No config file, checked whole pc

### ISSUE THREAD

**Issue by mustardau** [TheCBProject/CodeChickenLib#280]
looked at many different guides and didn't help at all still crashing on initializing, been having this problem for the last hour now.

-----------------------------------------

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 1/16/20 2:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/util/ResourceUtils
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:53)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.util.ResourceUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.SecurityException: class "codechicken.lib.util.ResourceUtils"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 307619944 bytes (293 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                            | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                     | None                                     |
	| LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCH   | forge                             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCH   | aether_legacy                     | 1.4.4             | aether_legacy-1.12.2-v1.4.4.jar                   | None                                     |
	| LCH   | biomesoplenty                     | 7.0.0.2291        | BiomesOPlenty-1.12-7.0.0.2291-universal.jar       | None                                     |
	| LCH   | cavern                            | 2.1.8             | Cavern_1.12.2-v2.1.8.jar                          | None                                     |
	| LCH   | clayworldgen                      | 1.1.0-1.12        | ClayWorldGen-1.1.0-1.12.0.jar                     | None                                     |
	| LCE   | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal (1).jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LC    | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LC    | cxlibrary                         | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
	| LC    | dldungeonsjbg                     | 1.12.2            | DoomlikeDungeons-1.12.2-MC1.12.2.jar              | None                                     |
	| LC    | dungeonmobs                       | 5.7.0             | dungeonmobs-5.7.0-MC1.12.2.jar                    | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.73     | EnderCore-1.12.2-0.5.73.jar                       | None                                     |
	| LC    | jei                               | 4.15.0.291        | jei_1.12.2-4.15.0.291 (1).jar                     | None                                     |
	| LC    | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | enderio                           | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderiointegrationtic             | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderiobase                       | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderioconduits                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderiointegrationforestry        | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LC    | twilightforest                    | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar     | None                                     |
	| LC    | tconstruct                        | 1.12.2-2.13.0.171 | TConstruct-1.12.2-2.13.0.171.jar                  | None                                     |
	| LC    | enderiointegrationticlate         | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | ftblib                            | 5.4.1.80          | FTBLib-5.4.1.80.jar                               | None                                     |
	| LC    | enderiomachines                   | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | enderiopowertools                 | 5.1.55            | EnderIO-1.12.2-5.1.55.jar                         | None                                     |
	| LC    | ftbutilities                      | 5.3.0.79          | FTBUtilities-5.3.0.79.jar                         | None                                     |
	| LC    | ic2                               | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | journeymap                        | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LC    | morefurnaces                      | 1.10.5            | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
	| LC    | mysticalagriculture               | 1.7.1             | MysticalAgriculture-1.12.2-1.7.1.jar              | None                                     |
	| LC    | mysticalagradditions              | 1.2.10            | MysticalAgradditions-1.12.2-1.2.10.jar            | None                                     |
	| LC    | harvestcraft                      | 1.12.2zb          | Pam's HarvestCraft 1.12.2zb.jar                   | None                                     |
	| LC    | simplerecipes                     | 1.12.2c           | Pam's Simple Recipes 1.12.2c.jar                  | None                                     |
	| LC    | progressivebosses                 | 1.4.1             | ProgressiveBosses-1.4.1-mc1.12.x.jar              | None                                     |
	| LC    | projecte                          | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                       | None                                     |
	| LC    | ruins                             | 17.1              | Ruins-1.12.2.jar                                  | None                                     |

	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.87' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

**Comment by covers1624** [comment]
Please re-download ccl from curse forge. It appears to be corrupt
