### ISSUE TITLE
Problème minecaraft Moddé (codechickenlib)

### ISSUE THREAD

**Issue by 4854** [TheCBProject/CodeChickenLib#297]
j'ai un crash de mon minecarft en permanence à cause de Codechickenlib
voici le raport de plantage : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 4/17/20 6:02 PM
Description: Initializing game

java.lang.NoSuchMethodError: team.chisel.ctm.client.model.parsing.ModelLoaderCTM.getJSON(Lnet/minecraft/util/ResourceLocation;)Lcom/google/gson/JsonElement;
	at team.chisel.client.render.ModelLoaderChisel.accepts(ModelLoaderChisel.java:47)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:123)
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:235)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153)
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:223)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:150)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.client.render.ModelLoaderChisel.accepts(ModelLoaderChisel.java:47)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:123)
	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:235)
	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153)
	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:223)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:150)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 439508104 bytes (419 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version              | Source                                        | Signature                                |
	|:----- |:------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42                 | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99            | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | forge               | 14.23.5.2847         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | baubles             | 1.5.2                | Baubles-Mod-1.12.2.jar                        | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2441           | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCH   | codechickenlib      | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux        | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar       | None                                     |
	| LCH   | brandonscore        | 2.4.12               | Brandons-Core-1.12.2.jar                      | None                                     |
	| LCH   | buildcraftlib       | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.6            | buildcraft-all-7.99.24.6.jar                  | None                                     |
	| LCH   | ctm                 | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCH   | chisel              | MC1.12.2-0.2.0.31    | Chisel-Mod-1.12.2.jar                         | None                                     |
	| LCH   | draconicevolution   | 2.3.22               | Draconic-Evolution-Mod-1.12.2.jar             | None                                     |
	| LCH   | irontanks           | 1.12.2-2.1.0-beta.14 | Iron-Tanks-Mod-1.12.2.jar                     | None                                     |
	| LCH   | jei                 | 4.15.0.291           | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55        | Mantle-Mod-1.12.2.jar                         | None                                     |
	| LCH   | zaraklib            | 0.0.4                | ZarakLIB[0.0.6R].jar                          | None                                     |
	| LCH   | multibags           | 0.0.6                | MultiBags-Mod-1.12.2.jar                      | None                                     |
	| LCH   | nei                 | 2.4.3                | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !   �1Radicals Private.zip, ! # �4R�cA�eI�aN�bB�3O�9W �l�5RUSH �r# !.zip, �4PX�8PACK.zip
	Current Language: English (Australia)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor

**Comment by MineRobber9000** [comment]
This seems to be caused by Chisel, not CodeChickenLib.

Cela semble être causé par Chisel, pas CodeChickenLib.
