### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by LumenLumie66** [TheCBProject/CodeChickenLib#311]
Im using 1.12.2 and codechickenlib version 3.2.3.358. this si the log
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 9/8/20 1:09 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 359560824 bytes (342 MB) / 1073741824 bytes (1024 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                             | Signature                                |
	|:----- |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | forge               | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCH   | appliedenergistics2 | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | jei                 | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                          | None                                     |
	| LCH   | twilightforest      | 3.11.1020                | twilightforest-1.12.2-3.11.1020-universal[1].jar   | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCH   | thedragonlib        | 1.12.2-5.3.0             | thedragonlib-1.12.2-5.3.0.jar                      | None                                     |
	| LCH   | armorplus           | 1.12.2-11.28.0.69        | armorplus-1.12.2-11.28.0.69.jar                    | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCH   | bonsaitrees         | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                         | None                                     |
	| LCH   | carryon             | 1.12.3                   | carryon-1.12.2-1.12.3.15.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCE   | codechickenlib      | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal (2).jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux        | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LC    | cofhcore            | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar             | None                                     |
	| LC    | cofhworld           | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LC    | conarm              | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                          | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | ptrmodellib         | 1.0.4                    | PTRLib-1.0.4.jar                                   | None                                     |
	| LC    | props               | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
	| LC    | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | zerocore            | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
	| LC    | bigreactors         | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                | None                                     |
	| LC    | gravestone          | 1.10.3                   | gravestone-1.10.3.jar                              | None                                     |
	| LC    | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2 (1).jar                    | None                                     |
	| LC    | ichunutil           | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | inventorypets       | 2.0.6                    | inventorypets-1.12-2.0.6.jar                       | None                                     |
	| LC    | ironbackpacks       | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LC    | journeymap          | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LC    | jeresources         | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LC    | lucky               | 7.6.0                    | luckyblock-1.12.2-1.jar                            | None                                     |
	| LC    | projecte            | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LC    | moartinkers         | 0.6.0                    | moartinkers-0.6.0.jar                              | None                                     |
	| LC    | netherendingores    | 1.12.2-1.4.2             | Netherending-Ores-1.12.2-1.4.2.jar                 | None                                     |
	| LC    | harvestcraft        | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LC    | portalgun           | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | projectex           | 1.2.0.40                 | ProjectEX-1.2.0.40.jar                             | None                                     |
	| LC    | roguelike           | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LC    | thermalfoundation   | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal (1).jar | None                                     |
	| LC    | thermalexpansion    | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LC    | thermaldynamics     | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | simplyjetpacks      | 1.12.2-2.2.16.1          | SimplyJetpacks2-1.12.2-2.2.16.1.jar                | None                                     |
	| LC    | soundfilters        | 0.12.1_for_1.12          | SoundFilters-0.12.1_for_1.12.jar                   | None                                     |
	| LC    | taiga               | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                             | None                                     |
	| LC    | tcomplement         | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar                 | None                                     |
	| LC    | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LC    | uppers              | 0.0.6                    | Uppers-0.0.6.jar                                   | None                                     |
	| LC    | structurize         | 1.12.2-0.10.277-RELEASE  | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| LC    | minecolonies        | 1.12.2-0.11.841-ALPHA    | minecolonies-1.12.2-0.11.841-ALPHA-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017' Renderer: 'Radeon RX 590 Series'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)
If anyone can help me id greatly appreciate it

**Comment by Morpheus1101** [comment]
For starters, pasting the entire log is rather annoying, its handy to just use a service like pastebin and then paste the link in here.

For your issue itself .. it tells you the error and line in the config file thats causing the issue "dump_asm=true" is invalid .. remove that line or del the config file to generate a new one and see how you go.

**Comment by covers1624** [comment]
Follow the instructions here: https://github.com/TheCBProject/CodeChickenLib/issues/270
Alternatively don't try and use a config folder from 1.7.10
