### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by myrotom** [TheCBProject/CodeChickenLib#327]
I don't have the Config problem, for there is no Config file for chickenlib

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/16/20 2:50 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: codechickenlib Failed load class: codechicken.lib.CodeChickenLib
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.CodeChickenLib
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	... 36 more
Caused by: java.io.FileNotFoundException: C:\Users\Manfred\Twitch\Minecraft\Instances\Flex on the Children (Das System kann die angegebene Datei nicht finden)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:145)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 845079848 bytes (805 MB) / 1105723392 bytes (1054 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version      | Source                                          | Signature                                |
	|:----- |:------------------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                 | 1.12.2       | minecraft.jar                                   | None                                     |
	| LC    | mcp                       | 9.42         | minecraft.jar                                   | None                                     |
	| LC    | FML                       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LE    | codechickenlib            | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | None                                     |
	| L     | redstoneflux              | 2.1.1        | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| L     | cofhcore                  | 4.6.6        | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| L     | cofhworld                 | 1.4.0        | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| L     | forgemultipartcbe         | 2.6.2.83     | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| L     | microblockcbe             | 2.6.2.83     | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| L     | minecraftmultipartcbe     | 2.6.2.83     | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
	| L     | inventorypets             | 2.0.6        | inventorypets-1.12-2.0.6.jar                    | None                                     |
	| L     | jei                       | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| L     | mrtjpcore                 | 2.1.4.43     | MrTJPCore-1.12.2-2.1.4.43-universal.jar         | None                                     |
	| L     | projectred-core           | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-Base.jar            | None                                     |
	| L     | projectred-compat         | 1.0          | ProjectRed-1.12.2-4.9.4.120-compat.jar          | None                                     |
	| L     | projectred-integration    | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-integration.jar     | None                                     |
	| L     | projectred-transmission   | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-integration.jar     | None                                     |
	| L     | projectred-fabrication    | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-fabrication.jar     | None                                     |
	| L     | projectred-illumination   | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-lighting.jar        | None                                     |
	| L     | projectred-expansion      | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-mechanical.jar      | None                                     |
	| L     | projectred-relocation     | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-mechanical.jar      | None                                     |
	| L     | projectred-transportation | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-mechanical.jar      | None                                     |
	| L     | projectred-exploration    | 4.9.4.120    | ProjectRed-1.12.2-4.9.4.120-world.jar           | None                                     |
	| L     | thermalfoundation         | 2.6.7        | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| L     | thermalexpansion          | 5.5.7        | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
	| L     | thermalcultivation        | 0.3.6        | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| L     | thermaldynamics           | 2.5.6        | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
	| L     | thermalinnovation         | 0.3.6        | ThermalInnovation-1.12.2-0.3.6.1-universal.jar  | None                                     |
	| L     | vampirism                 | 1.6.2        | Vampirism-1.12.2-1.6.2.jar                      | None                                     |
	| L     | teamlapen-lib             | 1.6.2        | Vampirism-1.12.2-1.6.2.jar                      | None                                     |
	| L     | waystones                 | 4.1.0        | Waystones_1.12.2-4.1.0.jar                      | None                                     |
	| L     | matteroverdrive           | 0.7.0.0      | MatterOverdrive-1.12.2-0.7.1.0-universal.jar    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.67' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

**Comment by covers1624** [comment]
Your CodeChickenLib jar is corrupt and does not have a signature, re-download your file.
