### ISSUE TITLE
CodeChickenLib Error crashes Minecraft

### ISSUE THREAD

**Issue by Junkst** [TheCBProject/CodeChickenLib#332]
I've tried deleting the config/codechickenlib.cfg, and it doesn't fix my problem. Maybe this is a duplicate, but I haven't been able to find a fix to my problem. Here is the crash report.
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 12/29/20 8:57 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 351574120 bytes (335 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                          | Signature                                |
	|:----- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCH   | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| LCH   | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | appleskin           | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| LCH   | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar   | None                                     |
	| LCH   | buildcraftlib       | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                    | None                                     |
	| LCE   | codechickenlib      | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-deobf.jar       | None                                     |
	| LC    | redstoneflux        | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LC    | cofhcore            | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
	| LC    | cofhworld           | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
	| LC    | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LC    | thaumcraft          | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26 (1).jar            | None                                     |
	| LC    | twilightforest      | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
	| LC    | tconstruct          | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LC    | conarm              | 1.2.5.9                  | conarm-1.12.2-1.2.5.9 (1).jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LC    | doubledoors         | 1.2                      | doubledoors_1.12-1.2.jar                        | None                                     |
	| LC    | extrautils2         | 1.0                      | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| LC    | waila               | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LC    | moartinkers         | 0.6.0                    | moartinkers-0.6.0.jar                           | None                                     |
	| LC    | moremobss           | 1.0.0                    | More+Mobs+1.12.2.jar                            | None                                     |
	| LC    | mousetweaks         | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
	| LC    | natura              | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                      | None                                     |
	| LC    | stg                 | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                            | None                                     |
	| LC    | thermalfoundation   | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
	| LC    | thermalexpansion    | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
	| LC    | thermalcultivation  | 0.3.6                    | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
	| LC    | thermaldynamics     | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
	| LC    | thermalinnovation   | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar  | None                                     |
	| LC    | tcomplement         | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar              | None                                     |
	| LC    | tinkersjei          | 1.2                      | tinkersjei-1.2.jar                              | None                                     |
	| LC    | tinkertoolleveling  | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| LC    | wailaharvestability | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| LC    | wawla               | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | waystones           | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8681' Renderer: 'Intel(R) HD Graphics 630'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

All the issues I have read are from last year, so I hope people are still helping to fix issues here. This is also the first time I have used this website so let me know if I left anything out.

**Comment by covers1624** [comment]
You have downloaded the `deobf` Jar for CCL, you need the `universal` Jar.

**Comment by Junkst** [comment]
Thanks!
