### ISSUE TITLE
CodeChickenLib keeps on crashing my game

### ISSUE THREAD

**Issue by EterSky** [TheCBProject/CodeChickenLib#337]
Hello ! I wanted to play in a singleplayer survival world with multiple mods, CodeChickeLib included and when i start Minecraft i get this error message:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/11/21 8:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 257619032 bytes (245 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_F5 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version       | Source                                        | Signature                                |
	|:----- |:------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2        | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42          | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99     | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2838  | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | damageindicatorsmod | 1.0           | [1.12.2]DamageIndicatorsMod-3.5.1.jar         | None                                     |
	| LCH   | orbis_api           | 1.12.2-1.1.91 | Orbis-API-1.12.2.jar                          | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether              | 1.12.2-1.1.0  | Aether-2-Mod-1.12.2.jar                       | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | backpack            | 3.0.2         | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| LCE   | codechickenlib      | 3.2.3.358     | CodeChickenLib-1.12.2-3.2.3.358-deobf.jar     | None                                     |
	| LC    | customnpcs          | 1.12          | CustomNPCs_1.12.2-(05Jul20).jar               | None                                     |
	| LC    | jei                 | 4.16.1.301    | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LC    | nei                 | 2.4.3         | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | twilightforest      | 3.11.1021     | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.30' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.30
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
	
	
	How do i fix that ?

**Comment by covers1624** [comment]
You have the `deobf` jar installed, this jar is for mod developers, you want the `universal` jar.
