### ISSUE TITLE
error torch crash please help 1.12.2

### ISSUE THREAD

**Issue by piggy321** [TheCBProject/CodeChickenLib#345]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/8/21 11:22 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Multipart Plugin (minecraftmultipartcbe)
Caused by: java.lang.NoSuchFieldError: TORCH
	at codechicken.multipart.minecraft.Content.<clinit>(Content.java:33)
	at codechicken.multipart.minecraft.MinecraftMultipartMod.preInit(MinecraftMultipartMod.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod

**Comment by covers1624** [comment]
Provide the full crash report, don't cut pieces off.

But it seems that you have the `-deobf` jar not the `-universal` jar.
