### ISSUE TITLE
Cannot use MultipartSPH on a client world

### ISSUE THREAD

**Issue by GodlyIdea** [TheCBProject/CodeChickenLib#347]
Minecraft version 1.12
CodeChicken Lib 1.12.2-3.2.3.358-universal
(Error occurred in modpack Project Ozone 3 with all it's mods.)

The error is thrown when connecting to world:
`
java.lang.IllegalArgumentException: Cannot use MultipartSPH on a client world
	at codechicken.multipart.handler.MultipartSPH$$anonfun$getTileStream$1.apply(packethandlers.scala:111)
	at codechicken.multipart.handler.MultipartSPH$$anonfun$getTileStream$1.apply(packethandlers.scala:109)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:188)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at codechicken.multipart.handler.MultipartSPH$.getTileStream(packethandlers.scala:109)
	at codechicken.multipart.TileMultipart.getWriteStream(TileMultipart.scala:172)
	at codechicken.multipart.TileMultipart.getWriteStream(TileMultipart.scala:170)
	at codechicken.multipart.TMultiPart.getWriteStream(TMultiPart.scala:78)
	at codechicken.translocators.part.TranslocatorPart.sendDescUpdate(TranslocatorPart.java:125)
	at codechicken.translocators.part.TranslocatorPart.onNeighborChanged(TranslocatorPart.java:216)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:135)
	at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:448)
	at codechicken.multipart.BlockMultipart.func_189540_a(BlockMultipart.scala:223)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at lumien.randomthings.tileentity.redstoneinterface.TileEntityAdvancedRedstoneInterface.notifyTargets(TileEntityAdvancedRedstoneInterface.java:163)
	at lumien.randomthings.tileentity.redstoneinterface.TileEntityRedstoneInterface.updateRedstoneState(TileEntityRedstoneInterface.java:204)
	at lumien.randomthings.tileentity.redstoneinterface.TileEntityRedstoneInterface.func_73660_a(TileEntityRedstoneInterface.java:62)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.multipart.handler.MultipartSPH$$anonfun$getTileStream$1.apply(packethandlers.scala:111)
	at codechicken.multipart.handler.MultipartSPH$$anonfun$getTileStream$1.apply(packethandlers.scala:109)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:188)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at codechicken.multipart.handler.MultipartSPH$.getTileStream(packethandlers.scala:109)
	at codechicken.multipart.TileMultipart.getWriteStream(TileMultipart.scala:172)
	at codechicken.multipart.TileMultipart.getWriteStream(TileMultipart.scala:170)
	at codechicken.multipart.TMultiPart.getWriteStream(TMultiPart.scala:78)
	at codechicken.translocators.part.TranslocatorPart.sendDescUpdate(TranslocatorPart.java:125)
	at codechicken.translocators.part.TranslocatorPart.onNeighborChanged(TranslocatorPart.java:216)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:448)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:135)
	at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:448)
	at codechicken.multipart.BlockMultipart.func_189540_a(BlockMultipart.scala:223)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at lumien.randomthings.tileentity.redstoneinterface.TileEntityAdvancedRedstoneInterface.notifyTargets(TileEntityAdvancedRedstoneInterface.java:163)
	at lumien.randomthings.tileentity.redstoneinterface.TileEntityRedstoneInterface.updateRedstoneState(TileEntityRedstoneInterface.java:204)
	at lumien.randomthings.tileentity.redstoneinterface.TileEntityRedstoneInterface.func_73660_a(TileEntityRedstoneInterface.java:62)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)

-- Block entity being ticked --
Details:
	Name: randomthings:advancedredstoneinterface // lumien.randomthings.tileentity.redstoneinterface.TileEntityAdvancedRedstoneInterface
	Block type: ID #1040 (tile.advancedRedstoneInterface // lumien.randomthings.block.redstoneinterface.BlockAdvancedRedstoneInterface // randomthings:advancedredstoneinterface)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (351,125,-152), Chunk: (at 15,7,8 in 21,-10; contains blocks 336,0,-160 to 351,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #1040 (tile.advancedRedstoneInterface // lumien.randomthings.block.redstoneinterface.BlockAdvancedRedstoneInterface // randomthings:advancedredstoneinterface)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
`
Error is repeatable in single player world. (After saving and opening the world client crashes.)
Advanced Redstone Interface is targeting an (air) block which has translocators.
![image](https://user-images.githubusercontent.com/61575892/111716731-538dba80-885f-11eb-975a-b3a9ce7895c8.png)

**Comment by covers1624** [comment]
This appears to be an issue with Translocators, however, Translocators on 1.12 is not supported anymore. I recommend not accelerating ticks of Translocators.
