### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Fate6996** [TheCBProject/CodeChickenLib#348]
i keep getting this crash, as im trying to put draconium and iys dependancies in my modpack

**Comment by Fate6996** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  HCASM (HammerLib-1.12.2-2.0.6.26.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/30/21 12:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1293187880 bytes (1233 MB) / 1744830464 bytes (1664 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                             | Signature                                |
	|:----- |:------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                      | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | actuallyadditions   | 1.12.2-r152       | ActuallyAdditions-1.12.2-r152_1.jar                | None                                     |
	| LCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCH   | jei                 | 4.16.1.301        | jei_1.12.2-4.16.1.301_1.jar                        | None                                     |
	| LCH   | botania             | r1.10-361         | Botania+r1.10-361.jar                              | None                                     |
	| LCE   | codechickenlib      | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal (1).jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux        | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal (1).jar        | None                                     |
	| LC    | brandonscore        | 2.4.19            | BrandonsCore-1.12.2-2.4.19.214-universal (1).jar   | None                                     |
	| LC    | chickens            | 6.0.4             | chickens-6.0.4 (1).jar                             | None                                     |
	| LC    | compactmachines3    | 3.0.18            | compactmachines3-1.12.2-3.0.18-b278.jar            | None                                     |
	| LC    | cucumber            | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LC    | draconicevolution   | 2.3.27            | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LC    | hammercore          | 2.0.6.26          | HammerLib-1.12.2-2.0.6.26.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | projecte            | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LC    | expequiv            | 12.3.17           | ExpandedEquivalence-1.12.2-12.3.17.jar             | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LC    | extrautils2         | 1.0               | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LC    | gravestone          | 1.10.2            | gravestone-1.10.2.jar                              | None                                     |
	| LC    | inventorypets       | 2.0.12            | inventorypets-1.12-2.0.12.jar                      | None                                     |
	| LC    | ironchest           | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar                    | None                                     |
	| LC    | ironfurnaces        | 1.3.5             | ironfurnaces-1.3.5.jar                             | None                                     |
	| LC    | journeymap          | 1.12.2-5.7.0      | journeymap-1.12.2-5.7.0.jar                        | None                                     |
	| LC    | mekanism            | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LC    | mysticalagriculture | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
	| LC    | naturescompass      | 1.8.3             | NaturesCompass-1.12.2-1.8.3.jar                    | None                                     |
	| LC    | nuclearcraft        | 2.18y             | NuclearCraft-2.18y-1.12.2.jar                      | None                                     |
	| LC    | oreexcavation       | 1.4.137           | OreExcavation-1.4.137.jar                          | None                                     |
	| LC    | randomthings        | 4.2.7.4           | RandomThings-MC1.12.2-4.2.7.4.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | roost               | 2.0.10            | roost-1.12.2-2.0.10_1.jar                          | None                                     |
	| LC    | storagenetwork      | 1.7.11            | SimpleStorageNetwork-1.12.2-1.7.11.jar             | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |

	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
HCASM (HammerLib-1.12.2-2.0.6.26.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	HammerCore Debug Information: 
		Dependent Mods:
			-Expanded Equivalence (expequiv) @ 12.3.17

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270
