### ISSUE TITLE
codechickenlib

### ISSUE THREAD

**Issue by SOMBR4S** [TheCBProject/CodeChickenLib#365]
I dont know how to solve this error

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Inventory Tweaks (inventorytweaks)
Caused by: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setBoolean(Ljava/lang/String;Z)V
	at codechicken.nei.util.ItemStackMap.<clinit>(ItemStackMap.java:239)
	at codechicken.nei.NEIClientConfig.<clinit>(NEIClientConfig.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at invtweaks.integration.ItemListChecker.getNeiHidden(ItemListChecker.java:41)
	at invtweaks.integration.ItemListChecker.<init>(ItemListChecker.java:24)
	at invtweaks.InvTweaks.<init>(InvTweaks.java:106)
	at invtweaks.forge.ClientProxy.init(ClientProxy.java:51)
	at invtweaks.forge.InvTweaksMod.init(InvTweaksMod.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6919059416 bytes (6598 MB) / 7524057088 bytes (7175 MB) up to 7524057088 bytes (7175 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6016m -Xmx7552m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                  | Source                                        | Signature                                |
	|:----- |:--------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft       | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHI  | mcp             | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHI  | FML             | 8.0.99.99                | forge-1.12.2-14.23.5.2855-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge           | 14.23.5.2855             | forge-1.12.2-14.23.5.2855-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | codechickenlib  | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | harvest         | 1.12-1.2.8-25            | Harvest-1.12-1.2.8-25.jar                     | None                                     |
	| LCHE  | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | jei             | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | journeymap      | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCH   | nei             | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-deobf.jar     | None                                     |
	| LCH   | oreexcavation   | 1.4.150                  | OreExcavation-1.4.150.jar                     | None                                     |
	| LCH   | pixelmon        | 8.2.0                    | Pixelmon-1.12.2-8.2.0-universal.jar           | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8729' Renderer: 'Intel(R) UHD Graphics 630'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8729
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by covers1624** [comment]
You have downloaded the `deobf` version of NEI, You want the `universal` version.
