### ISSUE TITLE
go into your minecraft folder, the "config" folder includes all mod configs. Find "codechicken.cfg" (or something similar) and delete the file.

### ISSUE THREAD

**Issue by BoomBapRat** [TheCBProject/CodeChickenLib#372]
go into your minecraft folder, the "config" folder includes all mod configs. Find "codechicken.cfg" (or something similar) and delete the file.

To be as technical as I can about it (with my limited knowledge), the config was updated in a way that somehow broke old files. The telltale sign is that it complains of `ConfigParseException`, saying `Invalid value type d`.

_Originally posted by @MineRobber9000 in https://github.com/TheCBProject/CodeChickenLib/issues/239#issuecomment-498629363_

I tried this and there is no cfg file of that name thats created in the configs folder, I'm currently building a modpack for myself so maybe I should delete all the other mods' cfg files and remove all but CodeChickenLib?

**Comment by BoomBapRat** [comment]
Here is the crash log I keep getting, keep in mind there is no codechicken.cfg or codechickenlib.cfg file being created at all, and I'm also at a homeless shelter where the CurseForge website is blocked for most if not all mods I try to download:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/11/21 10:32 PM
XRay version: 58
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.packet.PacketCustom$ICustomPacketHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 98116744 bytes (93 MB) / 268435456 bytes (256 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UC	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	defaultsettings{2.1.16} [DefaultSettings] (DefaultSettings-Mod-1.7.10.jar) 
	UC	bdlib{1.9.4.109} [BD Lib] (BdLib-1.7.10.jar) 
	UC	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFH-Core-1.7.10.jar) 
	UC	advgenerators{0.9.20.123} [Advanced Generators] (Advanced-Generators-Mod-1.7.10.jar) 
	UC	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-Mod-1.7.10.jar) 
	UC	aiimprovements{0.0.1.19} [AI Improvements] (AI-Improvements-Mod-1.7.10.jar) 
	UC	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (Applied-Energistics-2-Mod-1.7.10.jar) 
	UC	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UC	Grinder{4.0.0} [Grinder] (Attachable-Grinder-Mod-1.7.10.jar) 
	UC	D3Core{1.1.2.41} [D3Core] (D3Core-1.7.10.jar) 
	UE	thutcore{2.0} [ThutCore] (Elevators-mod-by-thutmose-1.7.10.jar) 
	UE	ThutConcrete{2.0.0} [Thut's Concrete] (Elevators-mod-by-thutmose-1.7.10.jar) 
	UE	ThutTech{2.0.0} [Thut's Tech] (Elevators-mod-by-thutmose-1.7.10.jar) 
	UC	ShetiPhianCore{3.0.0} [ShetiPhian-Core] (ShetiPhianCore-1.7.10.jar) 
	UC	EnderTanks{rev16-beta1} [EnderTanks] (Ender-Tanks-Mod-1.7.10.jar) 
	UC	gravestone{0.7.10.3} [Gravestone] (EuhDawsons-GraveStone-Mod-1.7.10.jar) 
	UC	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-Mod-1.7.10.jar) 
	UE	ForgeMultipart{1.2.0.345} [Forge Multipart] (Forge-Multipart-1.7.10.jar) 
	UE	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (Forge-Multipart-1.7.10.jar) 
	UC	FpsReducer{mc1.7.10-1.10.3} [FPS Reducer] (FPS-Reducer-Mod-1.7.10.jar) 
	UC	IngameAccountSwitcher{7.0.1} [In-Game Account Switcher] (Ingame-Account-Switcher-Mod-1.7.10.jar) 
	UC	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UC	Lumberjack{1.1.0.21} [Lumberjack] (Lumberjack-mod-by-doubledoor-1.7.10.jar) 
	UE	Magneticraft{0.6.0-final} [Magneticraft] (Magneticraft-Mod-1.7.10.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-Mod-1.7.10.jar) 
	UC	Mekanism{9.1.1} [Mekanism] (Mekanism-Mod-Core-1.7.10.jar) 
	UC	MekanismGenerators{9.1.1} [MekanismGenerators] (Mekanism-Mod-Generators-1.7.10.jar) 
	UC	MekanismTools{9.1.1} [MekanismTools] (Mekanism-Mod-Tools-1.7.10.jar) 
	UC	MouseTweaks{2.4.4} [Mouse Tweaks] (Mouse-Tweaks-Mod-1.7.10.jar) 
	UC	PneumaticCraft{1.12.7-152} [PneumaticCraft] (PneumaticCraft-Mod-1.7.10.jar) 
	UC	RouterReborn{1.2.0.37} [Router Reborn] (Router-Reborn-Mod-1.7.10.jar) 
	UC	secretroomsmod{4.7.1} [The SecretRoomsMod] (Secret-Rooms-Mod-1.7.10.jar) 
	UC	Harvest{1.7.10-1.0.0-2} [Harvest] (SimpleHarvest-Mod-1.7.10.jar) 
	UC	StorageDrawers{1.7.10-1.10.8} [Storage Drawers] (Storage-Drawers-Mod-1.7.10.jar) 
	UC	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (Thermal-Foundation-Mod-1.7.10.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-Mod-1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	UC	TMechworks{0.2.15.106} [Tinkers' Mechworks] (Tinkers-Mechworks-Mod-1.7.10.jar) 
	UC	trophyslots{1.3.0} [Trophy Slots] (Trophy-Slots-Mod-1.7.10.jar) 
	UC	WailaHarvestability{1.1.6} [Waila Harvestability] (Waila-Harvestability-Mod-1.7.10.jar) 
	UC	XaeroMinimap{1.15.2} [Xaero's Minimap] (Xaeros_Minimap_1.15.2_Forge_1.7.10.jar) 
	UE	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (Forge-Multipart-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7870' Renderer: 'Intel(R) UHD Graphics 620'
	CoFHCore: -[1.7.10]3.1.4-329
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	ThermalFoundation: -[1.7.10]1.2.6-118
	TConstruct Environment: Environment healthy.
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7870
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by covers1624** [comment]
1.7.10 is not supported.

However, installing CodeChickenCore, will resolve your issues.

**Comment by BoomBapRat** [comment]
i have both and it still has an issue, if need be i can send my current modpack in the form of a zip file or sum

**Comment by BoomBapRat** [comment]
> 1.7.10 is not supported.
> 
> However, installing CodeChickenCore, will resolve your issues.

@covers1624 i have both and it still has an issue, if need be i can send my current modpack in the form of a zip file or sum

**Comment by MineRobber9000** [comment]
Redownload the mods then.
