### ISSUE TITLE
Strange crash when initializing mod

### ISSUE THREAD

**Issue by anna328p** [TheCBProject/CodeChickenLib#39]
CodeChickenLib-1.10.2-2.4.1.101-universal.jar Minecraft 1.10.2-forge1.10.2-12.18.3.2234 Java openjdk version "1.8.0_121"

Log: https://gist.github.com/dkudriavtsev/1b43d003eb24d61b8440f32f017b269e

Relevant section: 

```
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/RenderItem
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:503)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.RenderItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer codechicken.lib.asm.RenderHookTransformer@1ef48e49 from coremod CCLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 11 more
Caused by: java.lang.RuntimeException: java.io.IOException: No such file or directory
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:177)
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:182)
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:186)
	at codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformerList.transform(ModularASMTransformer.java:53)
	at codechicken.lib.asm.ModularASMTransformer.transform(ModularASMTransformer.java:328)
	at codechicken.lib.asm.RenderHookTransformer.transform(RenderHookTransformer.java:18)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
	... 13 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:163)
	... 19 more
```

https://chat.stackexchange.com/transcript/message/35591374#35591374

**Comment by covers1624** [comment]
Update your mods, you are a solid 100 builds behind on CCL..

**Comment by anna328p** [comment]
Newest version gives similar issue, let me test it again

**Comment by anna328p** [comment]
```
net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 2/21/17 6:07 PM
Description: Initializing game

java.lang.NoClassDefFoundError: Lnet/minecraft/client/renderer/ItemRenderer;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at Config.getDefaultResourcePack(Config.java:1161)
	at Config.getResourcePackNames(Config.java:1140)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:159)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:441)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.ItemRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer codechicken.lib.asm.CCL_ASMTransformer@b2da3a5 from coremod CCLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
Caused by: java.lang.RuntimeException: java.io.IOException: No such file or directory
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:177)
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:182)
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:186)
	at codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformerList.transform(ModularASMTransformer.java:61)
	at codechicken.lib.asm.ModularASMTransformer.transform(ModularASMTransformer.java:336)
	at codechicken.lib.asm.CCL_ASMTransformer.transform(CCL_ASMTransformer.java:29)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249)
	... 20 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at codechicken.lib.asm.ASMHelper.dump(ASMHelper.java:163)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at Config.getDefaultResourcePack(Config.java:1161)
	at Config.getResourcePackNames(Config.java:1140)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:159)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:441)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.9.8-1-ARCH
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 128344968 bytes (122 MB) / 415191040 bytes (395 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2234 Optifine OptiFine_1.10.2_HD_U_D1 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2234.jar) 
	UCH	Forge{12.18.3.2234} [Minecraft Forge] (forge-1.10.2-12.18.3.2234.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.4.218-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.3.jar) 
	UCH	CodeChickenLib{2.5.4.218} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.4.218-universal.jar) 
	UCH	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCH	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCH	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.13' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2234
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D1
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 378.13
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

With CCL build 218

**Comment by ArtOfCode-** [comment]
From what limited debugging I did, `codechicken.lib.asm.ModularASMTransformer.transform` calls `codechicken.lib.asm.ASMHelper.dump`, which runs into an IOException (presumably some component of the file path doesn't exist?) and re-throws as RuntimeException

**Comment by dkudriavtsev** [comment]
bump

**Comment by ArtOfCode-** [comment]
@dkudriavtsev Bumping GH issues does *literally nothing* except piss the maintainers off.

**Comment by covers1624** [comment]
Yeah, don't bump. Whats happening here is somehow ccl is unable to generate a a folder in your minecraft directory. mc dir/asm/ccl_modular/
No idea why this is broken, someone with more linux experence than me should comment.

**Comment by ArtOfCode-** [comment]
@dkudriavtsev for now just manually create it and see if that works? Might also want to `sudo chown -R <your_user> <mc_dir>` and `sudo chmod -R 755 <mc_dir>`.

**Comment by anna328p** [comment]
Thanks for the tip.

**Comment by anna328p** [comment]
Getting the same crash even after creating the directory, it has all correct permissions...

**Comment by ArtOfCode-** [comment]
Should probably note that the game directory this is running under is non-standard; see http://chat.stackexchange.com/transcript/message/35644162#35644162

**Comment by anna328p** [comment]
Running the game as root temporarily fixed the problem

**Comment by covers1624** [comment]
So, is there anything my end i need to do, or was this solved.

**Comment by ArtOfCode-** [comment]
The issue isn't fixed - running as root is a temporary workaround, but shouldn't be a long-term solution.

**Comment by covers1624** [comment]
Well im a bit conflicted here, I can stop the IOE's from CCL but that wont stop other mods throwing exceptions when doing the same thing i do.. This should also affect config generation.

**Comment by allanf181** [comment]
Same here on minecraft server 1.11.2 
https://hastebin.com/cihezizuqi.vbs

**Comment by covers1624** [comment]
1.11 is highly beta, things are going to change a lot do NOT use it.

**Comment by janagyjr** [comment]
I am having a similar issue in 1.10.2

https://pastebin.com/duE2hDnm

Curse says I have the latest release version (updated 30 March 2017). 

I'm unsure if it's CodeChickenLib or another core mod. I'm going to be looking for similar reports in the other coremods respective forums/github/etc.

**Comment by covers1624** [comment]
You have a mod trying to load client stuff on the server. Look at your modlist. On the actual issue there is very little that i can do besides not creating directories.

**Comment by janagyjr** [comment]
Can you help me figure out which one? I'm not very good at reading bug reports.

**Comment by covers1624** [comment]
.. From crash report: FirEmerald's Block/Item model renderer API (Block and Item model API 1.0.jar),   RenderPlayerAPIPlugin (RenderPlayerAPI-1.10.2-1.1.jar)

**Comment by covers1624** [comment]
The server does no rendering. Anything clientside related does not belong on the server.

**Comment by janagyjr** [comment]
okay, thank you

**Comment by anna328p** [comment]
Any news on this?
