### ISSUE TITLE
Codechickenlib crash

### ISSUE THREAD

**Issue by NikoWB69** [TheCBProject/CodeChickenLib#407]
crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  WolfArmorCore (WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 5/25/22 6:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
	at codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
	at codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:58)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 464957872 bytes (443 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                                | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2            | minecraft.jar                                         | None                                     |
	| LCH   | mcp                                          | 9.42              | minecraft.jar                                         | None                                     |
	| LCH   | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore                                |                   | minecraft.jar                                         | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                         | None                                     |
	| LCH   | obfuscate                                    | 0.4.2             | minecraft.jar                                         | None                                     |
	| LCH   | ctm                                          | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	| LCH   | appliedenergistics2                          | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar                  | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCE   | codechickenlib                               | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-deobf.jar             | None                                     |
	| LC    | redstoneflux                                 | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar               | None                                     |
	| LC    | brandonscore                                 | 2.4.20            | BrandonsCore-1.12.2-2.4.20.162-universal.jar          | None                                     |
	| LC    | cdm                                          | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                                | None                                     |
	| LC    | cfm                                          | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                                | None                                     |
	| LC    | cgm                                          | 0.15.3            | cgm-0.15.3-mc1.12.2.jar                               | None                                     |
	| LC    | movingworld                                  | 1.12-6.353        | movingworld-1.12-6.353-full.jar                       | None                                     |
	| LC    | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar                   | None                                     |
	| LC    | draconicevolution                            | 2.3.28            | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar    | None                                     |
	| LC    | galacticraftcore                             | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar                 | None                                     |
	| LC    | galacticraftplanets                          | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar             | None                                     |
	| LC    | thanos_guantlet                              | 1.0.0             | Gaunlets_1.0.0.jar                                    | None                                     |
	| LC    | gravestone                                   | 1.10.3            | gravestone-1.10.3.jar                                 | None                                     |
	| LC    | waila                                        | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LC    | jei                                          | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                             | None                                     |
	| LC    | herobrine                                    | 0.5.4             | LegendOfHerobrine-1.12.2-0.5.4.jar                    | None                                     |
	| LC    | mekanism                                     | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                         | None                                     |
	| LC    | patchouli                                    | 1.0-23.6          | Patchouli-1.0-23.6.jar                                | None                                     |
	| LC    | twilightforest                               | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar         | None                                     |
	| LC    | wolfarmor                                    | 3.8.0             | WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar | e94e38a605842477f3ec218e6fcf781f6b3f7f89 |

	Loaded coremods (and transformers): 
WolfArmorCore (WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6' Renderer: 'AMD Radeon HD 8400 / R3 Series'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768

**Comment by NikoWB69** [comment]
ive already tried deleting cfg files didnt work someone please

**Comment by covers1624** [comment]
`CodeChickenLib-1.12.2-3.2.3.358-deobf.jar`

You have installed the -deobf version of CCL.

This version is for mod developers, You want the -universal version.
