### ISSUE TITLE
Issue With CodeChickenLib

### ISSUE THREAD

**Issue by JubbaJoe** [TheCBProject/CodeChickenLib#410]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.12.2-1.0.jar)
  ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.9.2_Forge_1.12 (1).jar)
  FutureMC (future-mc-0.2.10.1.jar)
  BlurPlugin (Blur-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/22/22 1:35 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:390)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.loadFactories(CCBlockStateLoader.java:83)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader$$Lambda$209/488606562.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.initialize(CCBlockStateLoader.java:73)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:59)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 373780136 bytes (356 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version                  | Source                                            | Signature                                |
	|:----- |:----------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCH   | mcp               | 9.42                     | minecraft.jar                                     | None                                     |
	| LCH   | FML               | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | RenderPlayerAPI   | 1.0                      | minecraft.jar                                     | None                                     |
	| LCH   | xaerominimap_core | 1.12.2-1.0               | minecraft.jar                                     | None                                     |
	| LCH   | obfuscate         | 0.4.2                    | minecraft.jar                                     | None                                     |
	| LCH   | orbis-lib         | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build411.jar               | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether            | 0.3.0                    | Aether-2-Mod-1.12.2.jar                           | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | jei               | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                         | None                                     |
	| LCH   | appleskin         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                       | None                                     |
	| LCH   | redstoneflux      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
	| LCH   | hoverboardmod     | 0.4.2.1                  | Arkifs-Hoverboard-Mod-1.12.2.jar                  | None                                     |
	| LCE   | codechickenlib    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia          | 3.3.0                    | Avaritia-Mod-1.12.2.jar                           | None                                     |
	| LC    | bibliocraft       | 2.4.6                    | BiblioCraft[v2.4.6][MC1.12.2].jar                 | None                                     |
	| LC    | blur              | 1.0.4-14                 | Blur-Mod-1.12.2.jar                               | None                                     |
	| LC    | cdm               | 0.4.1                    | cdm-0.4.1-mc1.12.2 (1).jar                        | None                                     |
	| LC    | cfm               | 6.3.0                    | cfm-6.3.0-mc1.12.2 (1).jar                        | None                                     |
	| LC    | forgelin          | 1.8.4                    | Forgelin-1.8.4.jar                                | None                                     |
	| LC    | llibrary          | 1.7.20                   | LLibrary-1.12.2.jar                               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | fossil            | 8.0.5                    | Fossils-and-Archeology-Revival-Mod-1.12.2.jar     | None                                     |
	| LC    | futuremc          | 0.2.6                    | future-mc-0.2.10.1.jar                            | None                                     |
	| LC    | durabilityviewer  | 1.6                      | Giselbaers-Durability-Viewer-Mod-1.12.2.jar       | None                                     |
	| LC    | inventorypets     | 2.0.15                   | inventorypets-1.12-2.0.15.jar                     | None                                     |
	| LC    | inventorytweaks   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest         | 1.12.2-7.0.67.844        | Iron-Chests-Mod-1.12.2.jar                        | None                                     |
	| LC    | lucky             | 7.6.0                    | Lucky-Block-Mod-1.12.2.jar                        | None                                     |
	| LC    | mcwfences         | 1.0.0                    | Macaws-Fences-and-Walls-Mod-1.12.2.jar            | None                                     |
	| LC    | rootsclassic      | 1.12.2-1.1.7             | Roots-Classic-Mod-1.12.2.jar                      | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LC    | torohealthmod     | 1.12.2-11                | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar       | None                                     |
	| LC    | vehicle           | 0.44.1                   | vehicle-0.44.1-mc1.12.2.jar                       | None                                     |
	| LC    | xaerominimap      | 22.9.2                   | Xaeros_Minimap_22.9.2_Forge_1.12 (1).jar          | None                                     |
	| LC    | phosphor-lighting | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50.jar                 | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LC    | supertools        | 1.12.2-null              | Vanilla+-Tools-Mod-1.12.2.jar                     | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
RenderPlayerAPIPlugin (RenderPlayerAPI-1.12.2-1.0.jar)
  api.player.forge.RenderPlayerAPITransformer
ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2 (1).jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_22.9.2_Forge_1.12 (1).jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
FutureMC (future-mc-0.2.10.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
BlurPlugin (Blur-Mod-1.12.2.jar)
  com.tterrag.blur.BlurTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.29' Renderer: 'NVIDIA GeForce GTX 980/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 497.29
	OpenGlRenderer: NVIDIA GeForce GTX 980/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by covers1624** [comment]
You have a corrupt mod in your mods folder. Please see recently closed issues before opening s new one.
