### ISSUE TITLE
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash

### ISSUE THREAD

**Issue by redahtheartist** [TheCBProject/CodeChickenLib#417]
Hi, i have an issue with CCL, and yes i looked at the issue here before submitting this, i tried both re-installing CCL and deleting the cofig file but both didn't work
~
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Exit Code: -1
~
Here's the crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_22.13.0_Forge_1.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.26.2_Forge_1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/9/22 5:05 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:139)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:390)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.loadFactories(CCBlockStateLoader.java:83)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader$$Lambda$206/513341170.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.initialize(CCBlockStateLoader.java:73)
	at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:59)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 423479360 bytes (403 MB) / 1146093568 bytes (1093 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version           | Source                                        | Signature                                |
	|:----- |:---------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft              | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp                    | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML                    | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                  | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | xaerominimap_core      | 1.12.2-1.0        | minecraft.jar                                 | None                                     |
	| LCH   | xaeroworldmap_core     | 1.12.2-1.0        | minecraft.jar                                 | None                                     |
	| LCH   | thedragonlib           | 1.12.2-5.3.0      | thedragonlib-1.12.2-5.3.0.jar                 | None                                     |
	| LCH   | armorplus              | 1.12.2-11.28.0.69 | armorplus-1.12.2-11.28.0.69.jar               | None                                     |
	| LCE   | codechickenlib         | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ctm                    | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LC    | desertland             | 0.2.4             | desertland-1.12.2-0.2.4.jar                   | None                                     |
	| LC    | eleccore               | 1.9.453           | ElecCore-1.12.2-1.9.453.jar                   | None                                     |
	| LC    | mcjtylib_ng            | 3.5.4             | mcjtylib-1.12-3.5.4.jar                       | None                                     |
	| LC    | elementaldimensions    | 0.4.0             | elementaldimensions-1.12-0.4.0.jar            | None                                     |
	| LC    | cfm                    | 6.3.0             | furniture-6.3.2-1.12.2.jar                    | None                                     |
	| LC    | futuristicrobotics1122 | 2                 | Futuristic-Robotics-Mod-1.12.2.jar            | None                                     |
	| LC    | healthbar              | 1.0.7             | Health-Bar-Mod-1.12.1.jar                     | None                                     |
	| LC    | inventorysorter        | 1.13.3+57         | inventorysorter-1.12.2-1.13.3+57.jar          | None                                     |
	| LC    | jei                    | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LC    | killagersmod           | 2                 | Killagers-Mod-1.12.2.jar                      | None                                     |
	| LC    | patchouli              | 1.0-23.6          | Patchouli-1.0-23.6.jar                        | None                                     |
	| LC    | tiffitlib              | 1.0.3             | tiffitlib-1.0.3.jar                           | None                                     |
	| LC    | sanity                 | 1.0.2             | Sanity-Mod-1.12.2.jar                         | None                                     |
	| LC    | snowvillage            | 1.12.2-1.0.0      | SnowVillage-Mod-1.12.2.jar                    | None                                     |
	| LC    | ether                  | 1.12.2            | The-Ether-Mod-1.12.2.jar                      | None                                     |
	| LC    | twilightforest         | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LC    | llibrary               | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | wearables              | 1.1.3             | Wearables-Mod-1.12.1.jar                      | None                                     |
	| LC    | xaerominimap           | 22.13.0           | Xaeros_Minimap_22.13.0_Forge_1.12.jar         | None                                     |
	| LC    | xaeroworldmap          | 1.26.2            | XaerosWorldMap_1.26.2_Forge_1.12.jar          | None                                     |
	| LC    | eleccoreloader         | 1.9.453           | ElecCore-1.12.2-1.9.453.jar                   | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_22.13.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
XaeroWorldMapPlugin (XaerosWorldMap_1.26.2_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.77' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
~

Thanks~<3

**Comment by covers1624** [comment]
Please check closed issues before submitting a new one.

You have a corrupt mod in your mods folder, find it and remove it.

**Comment by redahtheartist** [comment]
how do i know which one is courrpted?
