### ISSUE TITLE
CCL Caught an exception rendering a block

### ISSUE THREAD

**Issue by nerdman0** [TheCBProject/CodeChickenLib#423]
Im playing on a server and all the integrated dynamics facade blocks say that there was an error rendering them.

when it says see the log for more info, does it mean the server log or the client log.

**Comment by nerdman0** [comment]
ok I found it
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:-7857, y:4, z:-16116
  Block Class:   class org.cyclops.integrateddynamics.block.BlockCable
  Registry Name: integrateddynamics:cable
  Metadata:      0
  State:         integrateddynamics:cable
 Tile at position
  Tile Class:    class org.cyclops.integrateddynamics.core.tileentity.TileMultipartTicking
  Tile Id:       integrateddynamics:cable
  Tile NBT:      {rotatable:0b,lightLevels:{map:[]},ForgeData:{},facadeMeta:3,rotation:2,forceDisconnected:{valueType:"java.lang.Boolean",map:[{value:0b,key:0},{value:0b,key:1},{value:0b,key:2},{value:0b,key:3},{value:0b,key:5}]},redstoneInputs:{map:[]},realCable:1b,lastRedstonePulses:{map:[]},facadeBlockName:"chisel:factory",connected:{valueType:"java.lang.Boolean",map:[{value:0b,key:0},{value:0b,key:1},{value:0b,key:2},{value:0b,key:3},{value:1b,key:4},{value:1b,key:5}]},redstoneStrong:{map:[]},redstoneLevels:{map:[]},x:-7857,y:4,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},z:-16116,partContainer:{parts:[]},id:"integrateddynamics:cable"}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at org.cyclops.integrateddynamics.client.model.CableModelBase.getFacadeQuads(CableModelBase.java:140) ~[CableModelBase.class:?]
	at org.cyclops.integrateddynamics.client.model.CableModelBase.getGeneralQuads(CableModelBase.java:275) ~[CableModelBase.class:?]
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:52) ~[DynamicItemAndBlockModel.class:?]
	at org.cyclops.cyclopscore.client.model.DynamicItemAndBlockModel.func_188616_a(DynamicItemAndBlockModel.java:49) ~[DynamicItemAndBlockModel.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.handler$zch000$beforeRenderModel(BlockModelRenderer.java:545) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80) ~[bvm.class:?]
	... 5 more

**Comment by covers1624** [comment]
Provide your full log to IntegratedDynamics. This is not a CCL issue.
