### ISSUE TITLE
Crashing upon startup

### ISSUE THREAD

**Issue by vnila9726** [TheCBProject/CodeChickenLib#425]
I've checked what has been said regarding this issue for 1.12, but I do not have anything in my config file about codechickenlib. I've got as far as deleting all of my mods, re-installing them, and doing the same for forge and I'm still having issues despite no longer having the file downloaded. Any advice?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  GenderLoadingPlugin ([1.12.2]Gender-1.7.0.jar)
  PatcherLoader (Thaumcraft6EnhancedPatcherServer-1.0.2.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 12/4/22 11:11 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: codechickenlib Failed load class: codechicken.lib.CodeChickenLib
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.CodeChickenLib
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	... 36 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@63e67888 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 42 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:53)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 567303856 bytes (541 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version           | Source                                        | Signature                                |
	|:----- |:-------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                  | 1.12.2            | minecraft.jar                                 | None                                     |
	| LC    | mcp                        | 9.42              | minecraft.jar                                 | None                                     |
	| LC    | FML                        | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                      | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | thaumcraft6enhancedpatcher | 1.0.2             | minecraft.jar                                 | None                                     |
	| LC    | gender                     | 1.7.0             | [1.12.2]Gender-1.7.0.jar                      | None                                     |
	| LC    | aether_legacy              | 1.5.3.2           | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LE    | codechickenlib             | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None                                     |
	| L     | jei                        | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| L     | mantle                     | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                      | None                                     |
	| L     | nei                        | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | None                                     |
	| L     | twilightforest             | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| L     | tconstruct                 | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |

	Loaded coremods (and transformers): 
GenderLoadingPlugin ([1.12.2]Gender-1.7.0.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
PatcherLoader (Thaumcraft6EnhancedPatcherServer-1.0.2.2.jar)
  com.sheenus.tc6enhancedpatcher.CasterManagerPatcher
  com.sheenus.tc6enhancedpatcher.ItemFortressArmorPatcher
  com.sheenus.tc6enhancedpatcher.ItemVoidRobeArmorPatcher
  com.sheenus.tc6enhancedpatcher.ModConfigPatcher
  com.sheenus.tc6enhancedpatcher.PlayerEventsPatcher
  com.sheenus.tc6enhancedpatcher.ThaumcraftMaterialsPatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.32 30.0.13032.0' Renderer: 'AMD Radeon(TM) Graphics'

**Comment by covers1624** [comment]
You are using an unsupported version of CCL, this is not supported.

Please ensure you have downloaded CCL directly from CurseForge.
