### ISSUE TITLE
codechickenlib keeps crashing, 1.12.2 

### ISSUE THREAD

**Issue by VinnyThevin** [TheCBProject/CodeChickenLib#439]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.17.1_Forge_1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 6/1/23 6:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1768993680 bytes (1687 MB) / 2986344448 bytes (2848 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 7 total; -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version           | Source                                             | Signature                                |
	|:----- |:-------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | mcp                        | 9.42              | minecraft.jar                                      | None                                     |
	| LCH   | FML                        | 8.0.99.99         | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                      | 14.23.5.2860      | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore              |                   | minecraft.jar                                      | None                                     |
	| LCH   | xaerominimap_core          | 1.12.2-1.0        | minecraft.jar                                      | None                                     |
	| LCH   | opencomputers|core         | 1.7.7+5413028     | minecraft.jar                                      | None                                     |
	| LCH   | jei                        | 4.16.1.1000       | jei_1.12.2-4.16.1.1000.jar                         | None                                     |
	| LCH   | abyssalcraft               | 1.10.4            | AbyssalCraft-1.12.2-1.10.4.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | ctm                        | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCH   | appliedenergistics2        | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | bdlib                      | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LCH   | ae2stuff                   | 0.7.0.4           | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
	| LCH   | baubles                    | 1.5.2             | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | redstoneflux               | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | p455w0rdslib               | 2.3.161           | p455w0rdslib-1.12.2-2.3.161.jar                    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCH   | ae2wtlib                   | 1.0.34            | AE2WTLib-1.12.2-1.0.34.jar                         | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCH   | ic2                        | 2.8.222-ex112     | industrialcraft-2-2.8.222-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | galacticraftcore           | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar              | None                                     |
	| LCH   | armourers_workshop         | 1.12.2-0.51.0     | Armourers-Workshop-1.12.2-0.51.0.jar               | None                                     |
	| LCH   | attributefix               | 1.0.10            | AttributeFix-1.12.2-1.0.10.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | quark                      | r1.6-179          | Quark-r1.6-179.jar                                 | None                                     |
	| LCH   | autoreglib                 | 1.3-32            | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCH   | guideapi                   | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCH   | bloodmagic                 | 1.12.2-2.4.3-105  | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
	| LCH   | bookshelf                  | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | botania                    | r1.10-364         | Botania+r1.10-364.4.jar                            | None                                     |
	| LCE   | codechickenlib             | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal (1).jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | brandonscore               | 2.4.20            | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LC    | carryon                    | 1.12.3            | carryon-1.12.2-1.12.6.20.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LC    | chisel                     | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LC    | cofhcore                   | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LC    | cofhworld                  | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LC    | collective                 | 3.0               | collective-1.12.2-3.0.jar                          | None                                     |
	| LC    | thermalfoundation          | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LC    | draconicevolution          | 2.3.28            | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LC    | draconicadditions          | 1.17.0            | Draconic-Additions-1.12.2-1.17.0.45-universal.jar  | None                                     |
	| LC    | ebwizardry                 | 4.3.9             | ElectroblobsWizardry-4.3.9.jar                     | None                                     |
	| LC    | elevatorid                 | 1.3.14            | ElevatorMod-1.12.2-1.3.14.jar                      | None                                     |
	| LC    | energyconverters           | 1.3.7.30          | energyconverters_1.12.2-1.3.7.30.jar               | None                                     |
	| LC    | waila                      | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LC    | extracells                 | 2.6.5             | ExtraCells-1.12.2-2.6.5.jar                        | None                                     |
	| LC    | galacticraftplanets        | 4.0.2.280         | Galacticraft-Planets-1.12.2-4.0.2.280.jar          | None                                     |
	| LC    | mjrlegendslib              | 1.12.2-1.2.1      | MJRLegendsLib-1.12.2-1.2.1.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LC    | extraplanets               | 1.12.2-0.7.5      | ExtraPlanets-1.12.2-0.7.5.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LC    | opencomputers              | 1.7.7+5413028     | OpenComputers-MC1.12.2-1.7.7+5413028.jar           | None                                     |
	| LC    | zerocore                   | 1.12.2-0.1.2.9    | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
	| LC    | bigreactors                | 1.12.2-0.4.5.68   | ExtremeReactors-1.12.2-0.4.5.68.jar                | None                                     |
	| LC    | findme                     | 1.1.0             | findme-1.12.2-1.1.0-8.jar                          | None                                     |
	| LC    | forgelin                   | 1.8.4             | Forgelin-1.8.4.jar                                 | None                                     |
	| LC    | futuremc                   | 0.2.6             | future-mc-0.2.11.jar                               | None                                     |
	| LC    | hbm                        | hbm-1.8.3a-G      | hbm-1.8.3a-G.jar                                   | None                                     |
	| LC    | ironbackpacks              | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| LC    | ironchest                  | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LC    | harvestcraft               | 1.12.2zb          | Pam_s+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LC    | jehc                       | 1.7.2             | just-enough-harvestcraft-1.12.2-1.7.2.jar          | None                                     |
	| LC    | lostcities                 | 2.0.22            | lostcities-1.12-2.0.22.jar                         | None                                     |
	| LC    | mca                        | 6.1.0             | MCA-1.12.2-6.1.0-universal.jar                     | None                                     |
	| LC    | mcef                       | 1.11              | mcef-1.12.2-1.11b.jar                              | None                                     |
	| LC    | mcjtylib_ng                | 3.5.4             | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LC    | llibrary                   | 1.7.20            | llibrary-1.7.20-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | mowziesmobs                | 1.5.8             | mowziesmobs-1.5.8.jar                              | None                                     |
	| LC    | projectintelligence        | 1.0.9             | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| LC    | radixcore                  | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar               | None                                     |
	| LC    | rftools                    | 7.73              | rftools-1.12-7.73.jar                              | None                                     |
	| LC    | rftoolscontrol             | 2.0.2             | rftoolsctrl-1.12-2.0.2.jar                         | None                                     |
	| LC    | stg                        | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                               | None                                     |
	| LC    | theaurorian                | 1.12.2-Release    | theaurorian-1.12.2-release-may3021.jar             | None                                     |
	| LC    | thermalexpansion           | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LC    | thermaldynamics            | 2.5.6             | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LC    | tlauncher_custom_cape_skin | 1.4               | tlskincape_1.12.2-1.4.jar                          | None                                     |
	| LC    | treeharvester              | 4.0               | treeharvester_1.12.2-4.0.jar                       | None                                     |
	| LC    | veining                    | 1.3.2             | veining-1.3.2-1.12.x.jar                           | None                                     |
	| LC    | webdisplays                | 1.1               | webdisplays-1.12.2-1.1.jar                         | None                                     |
	| LC    | wct                        | 3.12.97           | WirelessCraftingTerminal-1.12.2-3.12.97.jar        | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LC    | xaerominimap               | 22.17.1           | Xaeros_Minimap_22.17.1_Forge_1.12.jar              | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
XaeroMinimapPlugin (Xaeros_Minimap_22.17.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  li.cil.oc.common.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	List of loaded APIs: 
		* AbyssalCraftAPI (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Biome (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Block (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Caps (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Condition (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Disruption (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Energy (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Entity (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Event (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Integration (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Internal (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Item (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Necronomicon (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Recipe (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Rending (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Ritual (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Spell (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Structure (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|Transfer (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* AbyssalCraftAPI|TransferCaps (1.30.0) from AbyssalCraft-1.12.2-1.10.4.jar
		* ae2wtlib|API (1.0.34) from AE2WTLib-1.12.2-1.0.34.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-7.jar
		* armourers_workshop_api (0.2.0) from Armourers-Workshop-1.12.2-0.51.0.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.68.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.4.3-105.jar
		* BotaniaAPI (93) from Botania+r1.10-364.4.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-1.0.2.45.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-1.0.2.45.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.6.1-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
		* Galacticraft API (1.1) from GalacticraftCore-1.12.2-4.0.2.280.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.8-63.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.16.1.1000.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.7+5413028.jar
		* QuarkAPI (4) from Quark-r1.6-179.jar
		* redstonefluxapi (2.1.1) from RedstoneFlux-1.12-2.1.1.1-universal.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.12.97.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.9.jar
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by VinnyThevin** [comment]
it worked fine before but its different now
