### ISSUE TITLE
Game crash when chiseling blocks with ReChiseled in iChisel

### ISSUE THREAD

**Issue by Chaos02** [TheCBProject/CodeChickenLib#446]
Hi - I'm getting a consistent game crash caused by CCL in combination with the iChisel from ReChiseled.
The crash happens when clicking a block variant in the iChisel (and possibly others) GUI.

I see that it advises to turn off a feature in the config and will do so but this is suboptimal.
just wanna say that I cannot find any CCL feature descriptions anywhere and maybe there needs to be some compatibility between the Library and Mod.

Greetings!

PS: The attached error repeats for all in x:={0..2} y:={1, 3}
It seems to depend on the block pattern selected in iChisel.
```
[08Aug.2023 16:21:21.694] [Render thread/ERROR] [codechicken.lib.render.block.CCBlockRendererDispatcher/]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:0, y:1, z:0
  Block Class:   class net.minecraft.world.level.block.Block
  Registry Name: minecraft:coal_block
  State:         Block{minecraft:coal_block}
 Tile at position
  Tile Class:    null
  Tile Id:       null
  Tile NBT:      null
This functionality can be disabled in the CCL config file.
You can also turn off player messages in the CCL config file.

net.minecraft.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:72) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBatched(CCBlockRendererDispatcher.java:70) ~[CodeChickenLib-1.18.2-4.1.4.488-universal.jar%23130!/:4.1.4.488]
	at team.chisel.client.gui.GuiHitechChisel.m_7286_(GuiHitechChisel.java:434) ~[Chisel_DEV-1.18.2-2.0.2-alpha.17.jar%23123!/:1.18.2-2.0.2-alpha.17]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6305_(AbstractContainerScreen.java:92) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at team.chisel.client.gui.GuiChisel.m_6305_(GuiChisel.java:110) ~[Chisel_DEV-1.18.2-2.0.2-alpha.17.jar%23123!/:1.18.2-2.0.2-alpha.17]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.2.9-universal.jar%23432!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.2.9-universal.jar%23432!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.IllegalStateException: BufferBuilder not started
	at com.mojang.blaze3d.vertex.BufferBuilder.m_6297_(BufferBuilder.java:358) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at com.mojang.blaze3d.vertex.BufferVertexConsumer.m_5483_(BufferVertexConsumer.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at com.mojang.blaze3d.vertex.VertexConsumer.m_5954_(VertexConsumer.java:33) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5954_(BufferBuilder.java:2566) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at com.mojang.blaze3d.vertex.VertexConsumer.m_85995_(VertexConsumer.java:110) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at com.mojang.blaze3d.vertex.BufferBuilder.m_85995_(BufferBuilder.java:1537) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.m_111023_(ModelBlockRenderer.java:153) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.m_111012_(ModelBlockRenderer.java:133) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:81) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.tesselateWithAO(ForgeBlockModelRenderer.java:77) ~[forge-1.18.2-40.2.9-universal.jar%23432!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:67) ~[client-1.18.2-20220404.173914-srg.jar%23427!/:?]
	... 23 more
```

**Comment by Chaos02** [comment]
Edit: now that I've found the config file, the exception catch is probably not the problem.
I will cross-reference this in an issue in ReChiseled.
