### ISSUE TITLE
Log4j error 1.18.2 (ArchLinux OpenJDK)

### ISSUE THREAD

**Issue by I2pRandom** [TheCBProject/CodeChickenLib#452]
I did a grep search across my mods files, this is the only mod with Log4j strings.

`
2024-01-19 03:53:29,970 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:236)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1120)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1045)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1037)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:651)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:247)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:293)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:626)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at MC-BOOTSTRAP/org.apache.logging.log4j@2.17.0/org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at MC-BOOTSTRAP/org.apache.logging.log4j@2.17.0/org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at MC-BOOTSTRAP/org.apache.logging.log4j@2.17.0/org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:76)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

2024-01-19 03:53:29,971 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2024-01-19 03:53:29,971 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2024-01-19 03:53:29,976 main ERROR Unable to locate appender "File" for logger config "root"
2024-01-19 03:53:29,976 main ERROR Unable to locate appender "DebugFile" for logger config "root"
`

**Comment by covers1624** [comment]
This has absolutely nothing to do with CCL. This is all happening waaaaaay before mod loading during BoostrapLauncher initialization.

I have no idea what your issue is. But its not CCL.
