### ISSUE TITLE
NoClassDefFoundError: Something to do with IContext

### ISSUE THREAD

**Issue by DiamondFusion** [TheCBProject/CodeChickenLib#48]
I've been having this problem for awhile, even after I updated CodeChickenLib to the latest version. I think it may be conflicting with another mod, but I can't for the life of me figure out which one.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/30/17 11:25 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/context/IContext
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:792)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/server/permission/context/IContext
	at com.lothrazar.cyclicmagic.ModCyclic.onInit(ModCyclic.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:790)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.server.permission.context.IContext
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.0-21-generic
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 363266176 bytes (346 MB) / 953962496 bytes (909 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2092 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2092.jar) 
	UCHI	Forge{12.18.1.2092} [Minecraft Forge] (forge-1.10.2-12.18.1.2092.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHI	monstersanddungeons{1.1} [Monsters and Dungeons] ([1.10.2] Monster And Dungeons v 1.1.jar) 
	UCHI	uncraftingTable{1.6.1-pre8} [Uncrafting Table] ([1.10.2]UncraftingTable-1.6.1-pre8.jar) 
	UCHI	advancedswords{1.3.0} [Advanced Swords] (advancedswords-1.3.0-[1.9.4].jar) 
	UCHI	agriculturalexpansion{r-1.2.0} [Agricultural Expansion] (AgriculturalExpansion[1.9.4][1.10.2]-r1.2.2.jar) 
	UCHI	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCHI	thedragonlib{1.10.2-1.3.1} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.1.jar) 
	UCHI	armorplus{1.10.2-8.5.3.4} [ArmorPlus] (armorplus-1.10.2-8.5.3.4.jar) 
	UCHI	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	UCHI	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHI	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	UCHI	brandonscore{2.1.4} [Brandon's Core] (BrandonsCore-1.10.2-2.1.4.92-universal.jar) 
	UCHI	ChestTransporter{2.5.5} [Chest Transporter] (ChestTransporter-1.10.2-2.5.5.jar) 
	UCHI	classiccombat{1.0.0} [Classic Combat] (ClassicCombat-1.0.0-1.10.2-universal.jar) 
	UCHI	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHI	compressedThings{1.10.2-1.2} [Compressed Things] (compressedthings-1.10.2-1.2.jar) 
	UCHI	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHI	cxlibrary{1.2.3} [CXLibrary] (cxlibrary-1.10.2-1.2.3.jar) 
	UCHI	JEI{3.14.3.403} [Just Enough Items] (jei_1.10.2-3.14.3.403.jar) 
	UCHE	cyclicmagic{1.10.14} [Cyclic] (Cyclic-1.10.2-1.10.14.jar) 
	UCHI	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.9.4-0.10.0.jar) 
	UCHI	draconicevolution{2.0.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.8.177-universal.jar) 
	UCHI	druidry{2016.9.26-1.9.4} [�2Druidry] (druidry(2016.9.26)(1.9.4).jar) 
	UCHI	everlastingabilities{1.2.4} [EverlastingAbilities] (EverlastingAbilities-1.9.4-1.2.4.jar) 
	UCHI	expandedbonemeal{1.0.0} [ExpandedBonemeal] (expandedbonemeal-1.10.2-1.0.0.jar) 
	UCHI	GoodRecipesMod{1.0.0} [GoodRecipesMod] (GoodRecipesMod Forge 1.10.2.jar) 
	UCHI	grimpack{3.4.17.53} [Grim Pack] (Grim Pack-1.10.2-3.4.17.53.jar) 
	UCHI	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UCHI	ironbackpacks{1.10.2-2.2.17} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.17.jar) 
	UCHI	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.10.2-2.1.jar) 
	UCHI	librarianlib{1.7} [LibrarianLib] (librarianlib-1.8.jar) 
	UCHI	lucky{7.3.0} [Lucky Block] (LuckyBlock_1-10-2_v7-3-0.zip) 
	UCHI	moreanvils{6.1.2} [More Anvils] (MoreAnvils-6.1.2.jar) 
	UCHI	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCHI	moreplayermodels{1.10.2} [MorePlayerModels] (MorePlayerModels_1.10.2(11nov16).jar) 
	UCHI	MultiPageChest{1.7.0} [Multi Page Chest] (MultiPageChest-1.10-1.7.0.jar) 
	UCHI	botanicaladdons{1.10} [Natural Pledge] (NaturalPledge-r1.10.jar) 
	UCHI	samsapples{1.1.5} [Power Apples] (PowerApples-1.10.2-1.1.5.jar) 
	UCHI	randomore{1.3.1} [Randomite Ore] (RandomiteOre-1.3.1-MC1.10.2.jar) 
	UCHI	SaltMod{1.8.d} [Salty Mod] (SaltyMod-1.10.2-1.8.d.jar) 
	UCHI	sentries{1.0} [sentries] (sentries-1.1.jar) 
	UCHI	sfartifacts{1.5.2.1} [SFArtifacts] (sfartifacts-1.10.2-2.0.1.jar) 
	UCHI	superores{1.7} [Super Ores] (SuperOres-1.7.jar) 
	UCHI	tails{1.10.2-1.8.3} [Tails] (Tails-1.10.2-1.8.3.jar) 
	UCHI	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (torohealth-1.10.2-1.jar) 
	UCHI	touchofbeacon{1.0.1} [Touch of Beacon] (touchofbeacon-1.10.2-1.0-build-T4.jar) 
	UCHI	uncrafted{2.1.3} [Uncrafted Mod] (Uncrafted 1.10.2 (v.2.1.3).jar) 
	UCHI	uniquecrops{0.1.71} [Unique Crops] (uniquecrops-1.10.2-0.1.71.jar) 
	UCHI	utilityworlds{1.0.10} [Utility Worlds] (UtilityWorlds-1.10.2_1.0.10.jar) 
	UCHI	XaeroMinimap{1.12.4} [Xaero's Minimap] (Xaeros_Minimap_1.12.4_Forge_1.9.4.jar) 
	UCHI	librarianliblate{1.7} [LibrarianLib Stage 2] (librarianlib-1.8.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.3.jar)
  cubex2.cxlibrary.CoreModTransformer
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 17.1.0-devel' Renderer: 'Mesa DRI Intel(R) Haswell Mobile '
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports:

**Comment by covers1624** [comment]
This is not a CCL issue. Update forge.
