### ISSUE TITLE
[1.10.2] - codechicken.lib.model.blockstate.CCBlockStateLoader:load:132

### ISSUE THREAD

**Issue by Protheus** [TheCBProject/CodeChickenLib#61]
MC: 1.10.2
Forge: 2316
Codechickenlib: CodeChickenLib-1.10.2-2.5.9.267-universal
No texture pack used

I get below error when loading the MC. It doesn't happen always. Sometimes it happens 10x in a row and 11th time the game loads fine

Also not sure if this is related to codechickenlib.

**Pastebin**:
Log: https://pastebin.com/xMqsisRB
Crash: https://pastebin.com/nU4Q2e0P

I get:
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 6
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at com.google.gson.internal.Streams.parse(Streams.java:56)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at com.google.gson.JsonParser.parse(JsonParser.java:84)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at codechicken.lib.model.blockstate.CCBlockStateLoader.load(CCBlockStateLoader.java:54)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at codechicken.lib.model.blockstate.CCBlockStateLoader.handleLoad(CCBlockStateLoader.java:38)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_178331_a(ModelBlockDefinition.java)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.renderer.block.model.ModelBakery.func_188636_a(ModelBakery.java:219)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.renderer.block.model.ModelBakery.func_188632_a(ModelBakery.java:200)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177586_a(ModelBakery.java:185)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraftforge.client.model.ModelLoader.func_177586_a(ModelLoader.java:281)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1192)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:252)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:145)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:240)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[08:16:54] [Client thread/INFO]: [codechicken.lib.model.blockstate.CCBlockStateLoader:load:132]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by covers1624** [comment]
Mitigation has been added for the pending CCL3 release.

**Comment by Protheus** [comment]
thank you

**Comment by Protheus** [comment]
guess no 1.10.2 release :-(

**Comment by Neoslayer** [comment]
-- Head --
Thread: Client thread
Stacktrace:
    at codechicken.lib.model.loader.blockstate.CCBlockStateLoader.onTextureStitchPre(CCBlockStateLoader.java:126)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_113_CCBlockStateLoader_onTextureStitchPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:175)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:87)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:168)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at magic.launcher.Launcher.main(SourceFile:214)

I'm new to this site, playing MC over again, sending logs, et cetera

**Comment by covers1624** [comment]
Not the same issue.
