### ISSUE TITLE
[1.11.2] CCL / CoFH - Tesselating Leadstone Duct Crash

### ISSUE THREAD

**Issue by NicholasThong** [TheCBProject/CodeChickenLib#83]
Full Log: https://paste.ee/p/b6mBi

Stack Trace:
-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectByteBuffer.putFloat(Unknown Source)
	at net.minecraft.client.renderer.VertexBuffer.func_187315_a(VertexBuffer.java:347)
	at codechicken.lib.render.CCRenderState.writeVert(CCRenderState.java:187)
	at codechicken.lib.render.CCRenderState.render(CCRenderState.java:167)
	at codechicken.lib.render.CCModel.render(CCModel.java:460)
	at codechicken.lib.render.CCModel.render(CCModel.java:448)
	at cofh.thermaldynamics.render.RenderDuct.renderBase(RenderDuct.java:176)
	at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:394)
	at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:90)

-- Block being tessellated --
Details:
	Block type: ID #3052 (tile.cofh.duct // cofh.thermaldynamics.block.BlockDuct)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-299,66,-33), Chunk: (at 5,4,15 in -19,-3; contains blocks -304,0,-48 to -289,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:52)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:173)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1438)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1700)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)

I've used WorldEdit to remotely delete the leadstone duct, but placing another one at the same spot seems to cause another crash. Instantaneous crash upon loading into the area containing the duct. 

The duct is between two energy cells, one outputting to the other.

**Comment by covers1624** [comment]
~Can i get the full crash report and the full log, there is literelly no usefull information in that snipit, it generates the full thing for a reason you know..~ Ahh link at top. future reference, dont inclue a snipit otherwise we assume stuff like that.

**Comment by covers1624** [comment]
Can you remove optifine and try again please?

**Comment by NicholasThong** [comment]
Noted for future instances I submit reports.

Unfortunately I already reconfigured the setup for the energy cells, but I'll pull a backup of the server tomorrow morning and try it out in singleplayer to see if I can reproduce the issue.

**Comment by tgstyle** [comment]
I am seeing it happen in 1.12.1 placing a refined storage export bus.

https://gist.github.com/tgstyle/ade9f20e018f944c512d6bc3a34202c4

Edit: This is odd I know, but I removed the duct it referenced, then was able to place the export bus. Then placed the duct back with no issue...

Edit2: Reloading crashed with the same error.

**Comment by NicholasThong** [comment]
Cant seem to reproduce the issue. Weird interaction between a leadstone duct and a energy cell. I guess the issue can marked as resolved?
